### ISSUE TITLE
utterances doesn't connect to GitHub account - Chrome on Android

### ISSUE THREAD

**Issue by mwallner** [utterance/utterances#100]
Even though utterances successfully authorized as GitHub App, it doesn't work on mobile Chrome (Android).

![image](https://user-images.githubusercontent.com/5354972/50680290-6eb9da00-1007-11e9-92a5-54613bf14bd7.png)

On the regular desktop browser, everything works as expected, the mobile version still shows "Sign in to comment". 
![image](https://user-images.githubusercontent.com/5354972/50680363-c8220900-1007-11e9-8183-631b322ecd9f.png)

When clicking the sign-in button, following screen is shown:

![image](https://user-images.githubusercontent.com/5354972/50680318-885b2180-1007-11e9-95d6-bb9f184f3d17.png)

Environment:
* Chrome 71.0.3578.99
* Android 8.1.0

**Comment by jdanyow** [comment]
This should be fixed now- let me know if you continue to have issues. Thanks for reporting :dancing_women:
