### ISSUE TITLE
It's possible to use foreign repository

### ISSUE THREAD

**Issue by phil-opp** [utterance/utterances#108]
It's possible to use an arbitrary foreign repository for comments, as long as this repository uses the utterances app too. Example: https://github.com/phil-opp/blog_os/issues/533

I assume that this issue was just a mistake, but utterances could be easily abused to spam repositories this way. It would be nice to have some kind of server side URL whitelist to prevent this.

**Comment by jdanyow** [comment]
Added support for an origin whitelist. Add a file named `utterances.json` to the root the repository the host's your comments.
```json
{
  "origins": ["https://os.phil-opp.com"]
}
```

**Comment by jdanyow** [comment]
Looks like you already have an utterances.json :+1: You should be all set. Earlier versions of utterances used this file. I had retired the whitelist logic a while back to reduce setup complexity.

**Comment by phil-opp** [comment]
@jdanyow Awesome, thank you!
