### ISSUE TITLE
SecurityError: The operation is insecure

### ISSUE THREAD

**Issue by newey01c** [utterance/utterances#11]
Firefox is complaining about an operation being insecure, but I'm not sure what. Haven't had time to debug yet, but I'm using FF 55.0.2 (64-bit). I've attached a screenshot of the error output as well.

Happy to share the blog URL if that's helpful at all - it's entirely possible (read: likely) that I'm being a doofus. Really nice idea though, and nice execution - love the idea of GH issues as comments.

![screenshot from 2017-09-19 16-26-52](https://user-images.githubusercontent.com/29257724/30600596-ca0f377a-9d57-11e7-9e4d-a61d65e21b8f.png)

**Comment by newey01c** [comment]
OK so after a little further hunting, it appears that the error is on L94 of client.js, which corresponds to the LocalStorage operations in the Token class in oauth.ts. I think Firefox is blocking LocalStorage requests from iFrames/included HTML.

**Comment by jdanyow** [comment]
I'm not able to repro this in firefox standard or developer edition

**Comment by newey01c** [comment]
Minimal working example: [site](https://newey01c.github.io/testing) [repo](https://github.com/newey01c/testing)

Using Firefox 56.0, Ubuntu 16.04.

**Comment by jdanyow** [comment]
@newey01c thanks for reporting this, I was able to reproduce by opening `about:config` in firefox and setting the `dom.storage.enabled` property to `false`.

This is now fixed, apologies for the delay.
