### ISSUE TITLE
Comments showing on home page

### ISSUE THREAD

**Issue by dend** [utterance/utterances#12]
As an example, on this page there are comments:
https://dennisdel.com/blog/

However, when we look at the comment, it should be associated with a different page:
https://dennisdel.com/blog/building-docs-for-nuget-packages-with-vsts-and-github-pages/

**Comment by jdanyow** [comment]
You're using the "issue title contains page url" mode. This works well for blog post pages but not for a homepage. All your issue titles will match `https://dennisdel.com/blog/`:

https://github.com/dend/blog/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20%22https%3A%2F%2Fdennisdel.com%2Fblog%2F%22%20


For home pages it's better to use a hard coded search term or issue number.

For example, you could create an issue titled "homepage" and use this configuration:

```html
<script src="https://utteranc.es/client.js"
        repo="dend/blog"
        branch="master"
        issue-term="homepage"
        async>
</script>
```

Or if the homepage issue already exists, reference it by number:

```html
<script src="https://utteranc.es/client.js"
        repo="dend/blog"
        branch="master"
        issue-number="123"
        async>
</script>
```

The trick here will be preserving your existing configuration on "blog post" pages while using a hard-coded term on the home page. Here's how you could do that:

```diff
- <script src="https://utteranc.es/client.js"
-         repo="dend/blog"
-         branch="master"
-         issue-term="url"
-         async>
- </script>
+ <script id="utterances-bootstrapper">
+   var s = document.createElement('script');
+   s.src = 'https://utteranc.es/client.js';
+   s.async = true;
+   s.setAttribute('repo', 'dend/blog');
+   s.setAttribute('branch', 'master');
+   s.setAttribute('issue-term', /^\/blog\/?$/.test(location.pathname) ? 'homepage' : 'url');
+ 
+   var me = document.getElementById('utterances-bootstrapper');
+   me.insertAdjacentElement('afterend', s);
+ </script>
```

**Comment by jdanyow** [comment]
@dend are you all set- can this be closed?

**Comment by dend** [comment]
@jdanyow thanks for the help! I fixed the template in this situation with a check on the title (there is only one page with a specific title in my set) to determine where not to render. This can be closed.

**Comment by jdanyow** [comment]
nice- thanks
