### ISSUE TITLE
Comments disappearing/re-appearing

### ISSUE THREAD

**Issue by dexygen** [utterance/utterances#120]
The test comments I am leaving on my blog post https://dexygen.github.io/blog/articles/2019/01/04/AccidentallyDeclarative.html are disappearing/re-appearing.  There should be two comments "test" and "where did my comment go", but only one of them ever appears, and it alternates.  In fact, a hard refresh caused it to change (but not change back on a subsequent hard refresh).  The two issues/comments can be found here: https://github.com/dexygen/ghio-comments-accidentally-declarative/issues

**Comment by thumbsu** [comment]
I think I have a same problem. https://quizzical-payne-46b418.netlify.com

**Comment by jdanyow** [comment]
@dexygen there's a race condition in your blog template / javascript.

The page begins with:
```html
<title>Dexygen: Software, Powerful and Simple</title>
```

Sometime later a script is changing the title:
![image](https://user-images.githubusercontent.com/1306747/52596510-5195d980-2e05-11e9-961f-78f7952ce2c9.png)

This is causing a different issue to load depending on whether the script has changed the title before utterances runs.  

I recommend using pathname to avoid issues like this.
```diff
 <script src="https://utteranc.es/client.js"
         repo="dexygen/ghio-comments-accidentally-declarative"
-         issue-term="title"
+         issue-term="pathname"
         theme="github-light"
         crossorigin="anonymous"
         async>
 </script>
```

**Comment by dexygen** [comment]
@jdanyow Makes sense. I will follow your recommendation, keep an eye out for a couple of days, then let you know if you can close this.  Thanks for your attention.

**Comment by dexygen** [comment]
@jdanyow I've tested with 3 comments and everything's working as expected for me now

**Comment by jdanyow** [comment]
Great news- closing this 🍻

**Comment by bmh8993** [comment]
@jdanyow hi, I use pathname in issue-term but, still appear and disappear....
