### ISSUE TITLE
Comment box partially hidden

### ISSUE THREAD

**Issue by kiedtl** [utterance/utterances#133]
Trying out Utterances on the homepage, I noticed, after upvoting a comment, that the comment box was partially hidden:

![](http://kiedtl.surge.sh/images/utterences-screenshot-1.webp)

I didn't see anything in the console, and reloading fixed the issue entirely.
I am using Vivaldi Snapshot, which is based on Chrome.

**Comment by jdanyow** [comment]
thanks for reporting!
