### ISSUE TITLE
Auth flow fails on iOS

### ISSUE THREAD

**Issue by yawpitch** [utterance/utterances#146]
Everything works on desktop, but in iOS (currently 12.2) when using Safari I’m not logged in after the redirect and the comment widget is still disabled and displays “Sign in to Comment”.

I’ve tried it both when logged into Github and able to access it in other tabs and when fully logged out. When logged out I get the initial sign in page, but once signing in (with two factor) I’m seen as logged in for other Safari pages but not utterances.

For some reason I seem to be able to see an enabled comment widget on the https://utterances.es home page, but I get the same failure on, for instance, https://os.phil-opp.com.

**Comment by lahvak** [comment]
I think this is the same as #123.

**Comment by yawpitch** [comment]
It appears it is. If I turn off `Settings > Safari > Prevent Cross Site Tracking` and then reboot Safari I can comment.

**Comment by yawpitch** [comment]
I’ll close this as a duplicate of #123 and continue discussion there.
