### ISSUE TITLE
Can I delete or hide comments?

### ISSUE THREAD

**Issue by crisperdue** [utterance/utterances#153]
Is there a straightforward way to hide or delete comments?
So far I was just thinking of doing a couple of tests and
then deleting the test comments, but I think it might
be useful otherwise also.

I tried removing the "comment" label on the test comment,
but that did not seem to have any effect.

Thanks!

**Comment by donaldboulton** [comment]
Close the comment

**Comment by robb-romans** [comment]
I closed the issue holding the comments, but it had no effect. I could still make new comments. What is the right procedure to freeze comments for a post?

**Comment by jdanyow** [comment]
To freeze comments associated with a post, open the github issue associated with the post and click the 
":lock: Lock conversation" button (on the left side, below labels and participants).

Comments can be deleted on the github site using the "..." button on the comments.

**Comment by crisperdue** [comment]
@jdanyow Thanks that is great info.  I see that the "delete" action is now below
the "Lock conversation" button.  For me, deleting the utteranc bot message
did indeed delete the comment, though it was still there after
deleting my own original comment.

**Comment by saheelsapovadia** [comment]
interesting, trying!
