### ISSUE TITLE
I can see the comments, but I cannot add comments

### ISSUE THREAD

**Issue by nkbai** [utterance/utterances#174]
for example:
https://github.com/nkbai/blog/issues/1

when I visit my blog: http://stevenbai.top/post/first/

I can see the comments,
when I try to add comment, it failed:
```
https://api.github.com/repos/nkbai/blog/contents/utterances.json?ref=master
get response:
{
  "message": "Not Found",
  "documentation_url": "https://developer.github.com/v3/repos/contents/#get-contents"
}

https://api.github.com/repos/nkbai/blog/issues/1/comments

get response:
{
  "message": "Resource not accessible by integration",
  "documentation_url": "https://developer.github.com/v3/issues/comments/#create-a-comment"
}

```

and there is an error:
```
Error: utterances is not installed on nkbai/blog. If you own this repo, install the app. Read more about this change in the PR.
```

How to fix this problem?

**Comment by nkbai** [comment]
I try configure `Repository access` to `All repositories` ,it works. 
Why  cannot I configure to `Only select repositories`

**Comment by jdanyow** [comment]
I'm not able to open the link to your blog. The assets on cdn.bootcss.com seem to be hanging.
