### ISSUE TITLE
Replace invalid custom attributes with `data-*`

### ISSUE THREAD

**Issue by fengsi** [utterance/utterances#180]
Currently, many custom attributes used to initialize the app are actually invalid in HTML5, such as `repo`, `issue-term`, `theme`, etc.  This is not the end of the world, but definitely quite annoying in some validators.

A better approach (and the right one) would be to use the `data-*` attributes:
https://developer.mozilla.org/en-US/docs/Learn/HTML/Howto/Use_data_attributes

This should be a fairly easy fix.  However, since the wrong custom attributes were already used, the updated code may need to support both types of attributes.

**Comment by jdanyow** [comment]
You can use `data-repo`, `data-theme`, etc if you'd like.

**Comment by fengsi** [comment]
@jdanyow awesome! That was quick! Thank you! 🎉
