### ISSUE TITLE
What is the Privacy Policy

### ISSUE THREAD

**Issue by XANOZOID** [utterance/utterances#185]
Is there a privacy policy for utterances? How can I adapt my own privacy policy with the inclusion of the widget? 

Should I be including GitHub's privacy policy? Thanks!

**Comment by jdanyow** [comment]
I'll update and restore the old [privacy-policy.md](https://github.com/utterance/utterances/commit/0748a9b64b96616ae98550eaa02ba01d2d676e50)- the cookies section is out of date.
