### ISSUE TITLE
[Question] Reply notification

### ISSUE THREAD

**Issue by noties** [utterance/utterances#190]
Hello!

First of all - thanks for the `utterances`! I think it's a great way to provide commenting for a static website served via Github Pages (even natural!). I'm using it for my [blog](https://noties.io) and find that it does the job perfectly. 

So, the question. I was wondering if a comment-poster will receive a notification if a new comment was posted? 
* If not -> how can he/she receive it, will a `@mention` trigger a notification?
* else -> how can a user unsubscribe from them?

I'm sorry if this is an obvious question, I just don't have another Github account to test it.

Thanks!

**Comment by jdanyow** [comment]
Github will notify the user when someone posts a comment on a thread they're participating in. Utterances does not have notifications of it's own.

More info here:
- https://help.github.com/en/articles/about-notifications
- https://help.github.com/en/articles/managing-your-notifications
