### ISSUE TITLE
Setting custom css stylesheet using window.postMessage()

### ISSUE THREAD

**Issue by octoxalis** [utterance/utterances#197]
Why not overide **github** stylesheet with a user **custom** stylesheet using a `window.addEventListener("message", ...)` in **utterances** `<iframe>` ?
Just checking that the message event is to load an overriding stylesheet would allow anyone to provide a styling of its own.

**Comment by jdanyow** [comment]
This is not supported for a couple reasons:
- Maintenance: I wouldn't be able to continue improving utterances if I had to freeze the html/class structure to avoid breaking custom css that folks had written but I have no visibility into.
- Security: there are vulnerabilities that could be introduced by doing this, slim chance of this happening but I'd rather not risk it.

Why not contribute a custom theme instead?
