### ISSUE TITLE
How do I configure pagination?

### ISSUE THREAD

**Issue by hngerebara** [utterance/utterances#205]
How do I configure pagination? Looks like you have a non-configurable page size of 25 comments which doesn't seem to be working correctly. It loads all comments regardless I tried making an example post with more than 25 comments but it just displayed everything

**Comment by hngerebara** [comment]
Sorted this. I needed to have a minimum of 53 comments on my page for pagination to be implemented

**Comment by Gninoskcaj** [comment]
@hngerebara Can this Issue be closed?

**Comment by jdanyow** [comment]
@hngerebara closing this- can re-open if needed
