### ISSUE TITLE
issue created by utterances-bot starts with "undefined"

### ISSUE THREAD

**Issue by nancym** [utterance/utterances#207]
I just set up utteranc.es, which was easy and it just works so thank you for this! I tested it at the bottom of https://www.ii.com/meta/connect/, which created this issue: https://github.com/nancym/ii-issues/issues/1. My questions:

* Why does the first line of the issue on GitHub say "undefined"?
* Is there a way I can fix this in general rather than editing the issue on GitHub?

Thanks you,
N

PS - Comments are welcome on my site😃

**Comment by nancym** [comment]
Hello again, I don't know much about Javascript so I haven't tried to debug this myself (yet), but I thought of a possible reason that this is happening. I build my site with `hugo --minify` and, thanks to the minification, the source of my pages includes this:

```
<script src=https://utteranc.es/client.js repo=nancym/ii-issues issue-term=title theme=github-light crossorigin=anonymous async></script>
```

Note that all quotation marks were removed. Is it possible that is part of the problem?

I thought that maybe this only happens with the very first use of utteranc.es, but I just posted a comment on another page on my site and the same thing happend: The utterances-bot produced an issue that says:

```
undefined

https://www.ii.com/website-todo-done/
```

Does anyone have any suggestion for how to debug this?

Thanks!

**Comment by jdanyow** [comment]
utterances is not correctly handling pages which do not have a "description" meta tag.

```html
<meta name="description" content="... a description of the blog post ...">
```

**Comment by jdanyow** [comment]
This is fixed. Thanks for reporting.

**Comment by nancym** [comment]
Thank you for fixing this @jdanyow!

**Comment by ayushxx7** [comment]
I am facing the same problem. 
https://github.com/ayushxx7/ayush-mandowara-blog/issues/6#issue-860393285

**Comment by ayushxx7** [comment]
https://github.com/ayushxx7/ayush-mandowara-blog/issues/8 - Here it is not undefined, but the title of the whole blog itself.
Please help.

**Comment by ayushxx7** [comment]
I think my issue was probably related to how my gatsby site was rendering title and description. 
It is fixed now! 
References: 
- https://github.com/ayushxx7/ayush-mandowara-blog/issues/10
- https://github.com/ayushxx7/ayush-mandowara-blog/commit/f80fdd57244327eec29a514f7c30a334b8fea1e2
