### ISSUE TITLE
Samesite attribute is now mandatory

### ISSUE THREAD

**Issue by octoxalis** [utterance/utterances#212]
Chrome has a new recommendation:

`A cookie associated with a cross-site resource at http://utteranc.es/ was set without the `SameSite` attribute. A future release of Chrome will only deliver cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032.`

Idem for cloudflare.com

Please set this attribute.

**Comment by jdanyow** [comment]
Thanks, will do.

**Comment by jdanyow** [comment]
note- cloudflare has not fixed their cfuuid cookie.

**Comment by crguezl** [comment]
Is this issue fixed?

I am still having the same issue when using Chrome with my blogs

```
ull-esit-dsi-1819.github.io/:1 
A cookie associated with a cross-site resource at http://utteranc.es/ was set without the `SameSite` attribute. 
It has been blocked, as Chrome now only delivers cookies with cross-site requests 
if they are set with `SameSite=None` and `Secure`. 
You can review cookies in developer tools under Application>Storage>Cookies and see more details at
 https://www.chromestatus.com/feature/5088147346030592 and
 https://www.chromestatus.com/feature/5633521622188032
```

**Comment by joostmeijles** [comment]
Same issue here. How to fix it?

**Comment by jdanyow** [comment]
@joostmeijles could you share a link? I'm not seeing this warning anymore.

**Comment by joostmeijles** [comment]
> @joostmeijles could you share a link? I'm not seeing this warning anymore.

https://joost.meijles.com/xc9-jwt/

**Comment by nebrelbug** [comment]
@jdanyow I'm having the same problem.

**Comment by nebrelbug** [comment]
@jdanyow it only works when I disable 3rd-party cookies... is there some way to fix this?

**Comment by kaknut** [comment]
I am seeing the same warning message on my developer console.

**Comment by YunfeiZHAO** [comment]
I still have this problem , someone fixed that?

**Comment by danfleser** [comment]
How do I fix this? I have a nextjs ssr blog.
