### ISSUE TITLE
useDarkMode switching

### ISSUE THREAD

**Issue by donaldboulton** [utterance/utterances#229]
I use Gatsby and love utterances on react-with-utterances. I have implemented useDarkMode in my site and would like to know of some way to switch between light and dark with this module and others. 
This could be done with useState  in React hooks but not sure how to do it any clues.

**Comment by jdanyow** [comment]
You can send a message to utterances instructing it to change theme. Here's an example:

```ts
const message = {
  type: 'set-theme',
  theme: 'github-dark' // 'github-light', etc.. 
};
const iframe = document.querySelector('.utterances-frame');
iframe.contentWindow.postMessage(message, 'https://utteranc.es');
```

**Comment by donaldboulton** [comment]
I will try that, and get back to this with the full code for darkMode switching
Thanks
Donald Boulton
