### ISSUE TITLE
utterances requires too many permissions

### ISSUE THREAD

**Issue by rain-1** [utterance/utterances#23]
Hello I wanted to use this but when I went to send a comment it says it needs full access to edit my repos?

---------------

utterances by utterance wants to access your rain-1 account
￼
Repositories: Public only
This application will be able to read and write all public repository data. This includes the following:

* Code
* Issues
* Pull requests
* Wikis
* Settings
* Webhooks and services
* Deploy keys

**Comment by markknol** [comment]
I question this too. I'm consider using this too, but I am afraid it will discourage user if so many permissions are used.

**Comment by rain-1** [comment]
yeah. it is very worrying, luckily we can use the system without by posting on github issues.

It may be that github itself does not support more refined permissions, if that is the case then this application makes a really good case for it.

**Comment by phil-opp** [comment]
@jdanyow posted in another issue that they are working on more granular permissions: https://github.com/utterance/utterances/issues/1#issuecomment-366287183

**Comment by jdanyow** [comment]
fixed in #25 :rocket:

**Comment by LukasKalbertodt** [comment]
Hi there! 

I was trying to use utterances as I think it's a great idea! However, to login via GitHub, it requires the following permissions:

![image](https://user-images.githubusercontent.com/7419664/42864020-4f63f974-8a65-11e8-8aa9-0f13e9680cbd.png)

These permissions are somewhat vague and it's not immediately clear to me what this entails. I guess that this is GitHub's fault and you can't work with fewer permissions, but I wanted to ask to be sure. Could someone explain why exactly these permissions are required? Thanks :)

**Comment by jdanyow** [comment]
@LukasKalbertodt here’s more info:
https://github.com/MicrosoftDocs/visualstudio-docs/issues/619#issuecomment-368942234

**Comment by LukasKalbertodt** [comment]
@jdanyow Thanks a lot, that answers my questions! :)
