### ISSUE TITLE
Failed to login utteranc.es on mobile browser with this TiddlyWiki site.

### ISSUE THREAD

**Issue by pimgeek** [utterance/utterances#235]
The website is built on TiddlyWiki, <https://wiki.hintsnet.com/#:about>, since it doesn't support inline javascript, I have to use hardcoded iframe to embed utteranc.es comment box.

I can login utteranc.es successfully on Desktop browser, but not on iOS (iPhone Xr, iOS 12.4.1) Safari or Brave Browser. I can confirm Blocking Cross-Site Tracking option is turned off.

Have tried many different method, and searched through past issues but haven't found a solution.

Can you help checking my website for potiential code error? ( my Wordpress site's utteranc.es comment box is OK for both mobile browsers and Desktop browsers -- <https://hintsnet.com/pimgeek/2019/10/09/a-trial-wechat-based-experimental-class-named-m-a-k-e/>)

Thanks in advance!

**Comment by jdanyow** [comment]
closing, as I don't have the bandwidth to debug your site. Hope you find a solution!
