### ISSUE TITLE
How far can I go with my custom theme?

### ISSUE THREAD

**Issue by dutzi** [utterance/utterances#239]
Hey,

Awesome project. It seems really polished and well made. Great job!

My question is regarding themes, I want to create a minimal theme for my blog, something that looks like this:

![image](https://user-images.githubusercontent.com/927310/71819680-4b4fc200-3095-11ea-968a-3f57d38a67cb.png)

Before I start working on it I wanted to ask, will such a theme be approved?

**Comment by jdanyow** [comment]
Cool theme :+1: 
The only constraints I have are:
1. Stick to overriding scss variables. This will ensure your theme doesn't break when utterances updates to the latest version of [primer](https://primer.style/).
2. Aim for at least WCAG AA level color contrast.
    https://webaim.org/resources/contrastchecker/

If you need to do more than that, I'd recommend forking the project. I can help you get up and running if you run into any issues.

**Comment by dutzi** [comment]
Got it. Thanks!
