### ISSUE TITLE
integration with GitLab Pages?

### ISSUE THREAD

**Issue by ousia** [utterance/utterances#240]
@jdanyow,

would it be possible to offer _utterances_ also for [GitLab Pages](https://pages.gitlab.io/)?

Many thanks for your help.

**Comment by jdanyow** [comment]
related #96

**Comment by jdanyow** [comment]
The main blocker for GitLab integration is their API requires authentication to search for issues. For utterances this means it's not a matter of abstracting away the GitHub/GitLab APIs and OAuth flows. We'd have to build a different experience for GitLab which is not something I want to take on at this time.

**Comment by gracinet** [comment]
Hi, just stumbled across this, and noticed that GitLab issues actually are listable/searchable by API

https://docs.gitlab.com/ee/api/issues.html#list-project-issues

Would that make you reconsider by any chance? I'm not fluent in JavaScript myself, but I have good knowledge of the GitLab code base and can provide a testing ground outside of gitlab.com if needed

**Comment by gracinet** [comment]
(GitLab API docs have been updated to clarify this in July 2020)
