### ISSUE TITLE
close comments

### ISSUE THREAD

**Issue by otech-nl** [utterance/utterances#242]
How can I close comments for a page?

When comments are closed, I would like to see existing comments, but block new ones.

**Comment by jdanyow** [comment]
Lock the issue to disable new comments

**Comment by otech-nl** [comment]
Thank you! Hadn't thought of that.
Does the utterance.es widget reflect that the issue is closed?

**Comment by jdanyow** [comment]
It does not indicate whether the associated issue is open/closed

**Comment by otech-nl** [comment]
I would like to help to add this feature.

Proposed functionality:

1. When an issue is not locked, comments work as before.
2. When an issue is locked, we show existing comments, but hide the possibility to add one.

I had a look at the code, and it seems this should already work:

* the `Issue` interface in [`github.ts:328`](https://github.com/utterance/utterances/blob/071b85f64735ab7d5579ec53d983c520dc001726/src/github.ts#L328) contains a boolean `locked`.
* this field is tested in [`utterance.ts:51`](https://github.com/utterance/utterances/blob/071b85f64735ab7d5579ec53d983c520dc001726/src/utterances.ts#L51) to bail out after `renderComments` (if any) and before `enableReactions` (if the user is authenticated) if the issue is locked.

What am I missing here?

**Comment by otech-nl** [comment]
Thanks. Works like a charm.

It may have worked before too, because I found out "closing" an issue is not the same as "locking" it. The issue must be **locked** to close utterance's comments.

**Comment by jdanyow** [comment]
Nice- I was trying to match GitHubs behavior where closed issues could still be commented on. Thanks for raising the issue with reactions
