### ISSUE TITLE
net::ERR_ABORTED 405 Cross Origin Error

### ISSUE THREAD

**Issue by mskian** [utterance/utterances#254]
Comment systems are not working due to this error

![Screenshot from 2020-01-28 15-30-58](https://user-images.githubusercontent.com/10300271/73253794-34f3dc80-41e3-11ea-81df-cb3c4e042c40.png)

**Comment by JaeYeopHan** [comment]
Same here. What's wrong with the token api server or cloudflare?
Is same issue with https://github.com/utterance/utterances/issues/91 ?

**Comment by phil-opp** [comment]
I'm also experiencing this issue on my site:
![image](https://user-images.githubusercontent.com/1131315/73255207-103a3d80-41c0-11ea-9b90-5fa869b788f8.png)

**Comment by Mikescops** [comment]
+1, even the demo page is down

**Comment by Cloud-Forge** [comment]
I know it doesn't help much, but same here ! +1
`Reason: CORS header 'Access-Control-Allow-Origin' missing`

**Comment by cmckee-dev** [comment]
Today was clearly a good day to implement utterance on my blog redesign. :joy: 

FireFox has an add-on I use for cors debugging called CORS Everywhere. It allows you to see the comments section when enabled. Still has issues with functionality though.

**Comment by crguezl** [comment]
Same here

**Comment by donghL-dev** [comment]
I am experiencing the same problem.

**Comment by jdanyow** [comment]
This is fixed. Caused by a configuration issue in the utterances CloudFlare worker.

**Comment by phil-opp** [comment]
@jdanyow Thanks for the quick fix! I can confirm that it works again.
