### ISSUE TITLE
Utterances not working today?

### ISSUE THREAD

**Issue by nancym** [utterance/utterances#255]
I thought it was just my site, for example in the "Discussion and Reactions" section at the bottom of https://www.ii.com/portal/content/ but when I came here to see if the code had changed, I discovered that the Utterances form is not showing up at either of these:

* https://utteranc.es/
* https://github.com/utterance/utterances

Instead it looks like the following with nothing below at the bottom of these two pages:

> try it out 👇👇👇

I hope this can be fixed for all of us.

Thank you for Utterances!

**Comment by phil-opp** [comment]
Seems to be caused by https://github.com/utterance/utterances/issues/254.

**Comment by jdanyow** [comment]
This is fixed. Caused by a configuration issue in the utterances CloudFlare worker.
