### ISSUE TITLE
I added @utterances-bot as a collaborator but.. Utterances uses the GitHub API to:

### ISSUE THREAD

**Issue by towhereim** [utterance/utterances#256]
I'm using private repo because I don't want to open my blog contents. So I added @utterances-bot as a collaborator an hour ago followed as you mentioned before.
but it's still showed me like 'Awaiting utterances-bot's response'.
Could you accept my invite?

Utterances uses the GitHub API to:
1. Create issues in your repo using the @utterances-bot GitHub user.
2. Post comments on your readers behalf using their GitHub account.

To use utterances with a private repo, you'll need to grant @utterances-bot permission to post issues in your repo (make it a collaborator) and ensure anyone who needs to post comments is also a collaborator. In other works, it's no different than if you wanted to allow folks to post issues/comments in your repo using the real GitHub site. This is probably fine if your scenario is an internal blog read by folks on your team but it's not going to work well for something public.

Let me know if this doesn't answer the question, I wasn't sure what your use-case was.

_Originally posted by @jdanyow in https://github.com/utterance/utterances/issues/203#issuecomment-536204114_

**Comment by jdanyow** [comment]
accepted the invite :heavy_check_mark:

**Comment by saptarshiguha** [comment]
Hmm, maybe a dumb question? I added @utterances-bot as a collaborator, but i see "Pending Invite" (and awaiting response). Why is this? Is there something else i ought be doing?

**Comment by gabrielenosso** [comment]
same issue..

**Comment by shawn-vincent-well** [comment]
Hi -- I tried adding utterance-bot to my repo as a collaborator yesterday (same issue -- don't want to open my repo publically).  It says "pending invite..."

Is there some way past this?  I'd love to use this tool if I could.
