### ISSUE TITLE
Search and automatically create issue by label

### ISSUE THREAD

**Issue by draveness** [utterance/utterances#257]
Utterances is a greate comment plugin, and I really want to migrate from gitalk to this. But gitment and gitalk create an issue with a customized label name, so it makes me harder to do the migration.

```javascript
      <script>
       const gitalk = new Gitalk({
         clientID: 'xxx',
         clientSecret: 'xxx',
         repo: 'blog-comments',
         owner: 'Draveness',
         admin: ['Draveness'],
         id: "{{ page.permalink }}", // gitment would find the issue with label name equals id here.
         distractionFreeMode: false,
         perPage: 100
       });
```

It would be great if we have this in Utterances.

**Comment by draveness** [comment]
And I have to say I'm not familiar with TypeScript but I dug around the source code. Maybe we could add an "issue-label" here for another option?

https://github.com/utterance/utterances/blob/dc97be64684c47e4d5aed1f9c8e7226261fd51ac/src/page-attributes.ts#L23-L31

**Comment by jdanyow** [comment]
I had not seen that pattern before. Is gitalk/gitment automatically creating the label for you?

- https://draveness.me/whys-the-database-data-loss
- https://github.com/draveness/blog-comments/issues/176

**Comment by draveness** [comment]
> I had not seen that pattern before. Is gitalk/gitment automatically creating the label for you?
> 
> * https://draveness.me/whys-the-database-data-loss
> * [draveness/blog-comments#176](https://github.com/draveness/blog-comments/issues/176)

Thanks for the reply, gitalk and gitment use a different strategy to create issues. The only approach to create an issue with these plugins is the repo owner accessing the page with their access token.

I think the non-admin can't create issues since they don't have the right to create a label.

**Comment by jdanyow** [comment]
Initially Utterances was a classic OAuth App. I switched to a GitHub App to alleviate security concerns.

It doesn't look like we'll be able to support the label strategy.

The draveness/blog-comments issues have the page's pathname in the issue title. You should be able to use the standard setup:
```html
<script src="https://utteranc.es/client.js"
        repo="draveness/blog-comments"
        issue-term="pathname"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

To quickly see this in action, go to one of your pages, for example: https://draveness.me/2017-summary

Then press F12 to open the browser's developer tools. Paste the following code into the console window and press enter.
```js
var script = document.createElement('script');
script.src = 'https://utteranc.es/client.js';
script.setAttribute('repo', 'draveness/blog-comments');
script.setAttribute('issue-term', 'pathname');
script.setAttribute('theme', 'github-light');
script.setAttribute('crossorigin', 'anonymous');
document.body.appendChild(script);
```

You will see utterances load with all your existing blog comments.

**Comment by draveness** [comment]
> To quickly see this in action, go to one of your pages, for example: https://draveness.me/2017-summary
> 
> Then press F12 to open the browser's developer tools. Paste the following code into the console window and press enter.

I wrote a ruby script to append the pathname to the issue title.
