### ISSUE TITLE
Possibility to add custom message to initial post 

### ISSUE THREAD

**Issue by markknol** [utterance/utterances#26]
Would it be possible to provide a custom/additional message to the initial post created by the bot?

```
<script src="https://utteranc.es/client.js"
        repo="[ENTER REPO HERE]"
        issue-term="[ENTER TERM HERE]"
        issue-body="[CUSTOM MESSAGE HERE]"
        async>
</script>
```

**Comment by jdanyow** [comment]
I think that would be an easy change.  Here's the current issue body template for reference:

https://github.com/utterance/utterances/blob/c31b9579a2bf0da3b9b7fd2a092993d9a4203ba7/src/github.ts#L194

Before I make any modifications, could you provide an example of what your custom template would look like? I want to make sure what I'm thinking about doing would meet the need.

**Comment by markknol** [comment]
Oh perfect. I would suggest to make it look like this

```json
 body: `# ${title}\n\n${description}\n\n ${customMessage}\n\n[${documentUrl}](${documentUrl})` 
```

**Comment by jdanyow** [comment]
Closing as there hasn't been a lot of folks interested in this enhancement.
