### ISSUE TITLE
How do I customize the style of the button?

### ISSUE THREAD

**Issue by allenfrostline** [utterance/utterances#261]
I've tried to follow the instructions in the `CONTRIBUTE.md` file but yarn start resulted in a syntax error eventually. Also I believe I'm able to toggle the styles of the `.utterences` and the corresponding `iframe` object. However, when I try to override the styles of more specific elements, e.g. the button, it just didn't work.

Is there any way to specify these styles using local css files? I believe this is really useful as different sites adopt different themes themselves. Full customization sounds reasonable to me.

**Comment by jdanyow** [comment]
Utterances does not support custom CSS. More info: https://github.com/utterance/utterances/issues/197#issuecomment-536203416.

Contributing a theme is currently the only way to change the styles.
