### ISSUE TITLE
issue-term URL - possible issue for different URLs

### ISSUE THREAD

**Issue by LordAmit** [utterance/utterances#279]
Hi,

Thank you for creating this awesome way of adding comments. I applied the URL format to issue, but it is not working as I thought it would in my **Jekyll** site. Better to show an example: 

This is what I am adding, 

```javascript
<script src="https://utteranc.es/client.js"
        repo="{{ site.utterances }}"
        issue-term="url"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

`site.utterances` is a variable, which is replaced by the name of my repo through the `config.yml` file when building the Jekyll site by using the following `key: value` pair, 

```
utterances: LordAmit/lordamit.github.io.comments
```

I tested it first by hosting the site first in the local server, and it showed up perfectly. Posted a comment, that worked too!

```https://github.com/LordAmit/lordamit.github.io.comments/issues/2#issuecomment-604775057```

Please note the title of the issue

```http://localhost:4000/blog/2018/04/23/higher-studies-in-usa/#2```

So, when I pushed my changes to the GitHub pages, I was not expecting it to show up in the deployed site since the URL is going to be different.  As you can see here, it shows up in the deployed site even though the URL in the issue title is not matching. 

```https://lordamit.github.io/blog/2018/04/23/higher-studies-in-usa/```

I thought I should inform you in case this was a flaw and not a design choice. 

Once again, thank you for making this awesome commenting system :)

**Comment by congerh** [comment]
I see you set `issue-term="pathname"` not `issue-term="url"` in your [site](https://lordamit.github.io/blog/2018/04/23/higher-studies-in-usa/), 

> **Issue title contains page pathname**
Utterances will search for an issue whose title contains the blog post's pathname URL component. If a matching issue is not found, Utterances will automatically create one the first time someone comments on your post.

> **Issue title contains page URL**
Utterances will search for an issue whose title contains the blog post's URL. If a matching issue is not found, Utterances will automatically create one the first time someone comments on your post.

In your case the query parameter is  
[blog/2018/04/23/higher-studies-in-usa/](https://api.github.com/search/issues?q=%22blog%2F2018%2F04%2F23%2Fhigher-studies-in-usa%2F%22%20type%3Aissue%20in%3Atitle%20repo%3ALordAmit%2Flordamit.github.io.comments&sort=created&order=asc)  
not  
[http://localhost:4000/blog/2018/04/23/higher-studies-in-usa/](https://api.github.com/search/issues?q=%22http%3a%2f%2flocalhost%3a4000%2fblog%2f2018%2f04%2f23%2fhigher-studies-in-usa%2f%22%20type%3Aissue%20in%3Atitle%20repo%3ALordAmit%2Flordamit.github.io.comments&sort=created&order=asc)

`localhost:4000` is only used in the local server, if you host your site on GitHub Pages and set `issue-term="url"`, Utterances will create an issue with your blog post's URL.

You can delete the [test issue](https://github.com/LordAmit/lordamit.github.io.comments/issues/2) and re-comment on your [site](https://lordamit.github.io/blog/2018/04/23/higher-studies-in-usa/) and Utterances will automatically create one with the URL you expect.

**Comment by LordAmit** [comment]
Uh oh, this is embarrassing. 
🤦‍♂ I remember getting an error from Github and repushing, but did not realize that my changes did not make it to the server. But that clears things up. Thank you so much @congerh
