### ISSUE TITLE
Support for authentication token?

### ISSUE THREAD

**Issue by iamashwin99** [utterance/utterances#280]
Passing a plain text repo URL seems like a bad idea. This could allow users to point his utterances script to any other users repo for comments (Take a look at this [issue](https://github.com/Pelican-Elegant/elegant/issues/602)). One possible solution is to have some kind of authentication.

**Comment by congerh** [comment]
It seems like your repository doesn't have `utterances.json`.
Try adding [utterances.json](https://raw.githubusercontent.com/utterance/utterances/master/utterances.json) to the root of your master branch:

```json
{
  "origins": ["https://utteranc.es"]
}
```

Update the `utterances.json` to include yours in the list of origins.
It may work.

**Comment by jdanyow** [comment]
To prevent unauthorized comments in your repo, add an `utterances.json` file to the master branch with the list of origins permitted to post in this repo.

*utterances.json*
```json
{
  "origins": ["https://elegant.oncrashreboot.com"]
}
```
