### ISSUE TITLE
Dark theme custom utterances-frame

### ISSUE THREAD

**Issue by terroo** [utterance/utterances#290]
When I use the Dark theme, the iframe (utterances-frame) turns white and has a white border, is it possible to remove these properties when the theme is dark?

![utterances-frame-white](https://user-images.githubusercontent.com/41500739/78574636-a615c880-7800-11ea-9fa2-aacb2da152ae.png)

**Comment by raprocks** [comment]
Het @terroo have you made it work?

**Comment by bender2k14** [comment]
How does the utterances homepage avoid this problem?

![2020-06-23_20-20-42_142_chrome](https://user-images.githubusercontent.com/34664007/85486361-1d513200-b590-11ea-9770-682218a6a01f.png)

**Comment by loreanvictor** [comment]
This is not an issue with utterances. The embedded HTML document and the body seem to have `transparent` backgrounds.
However, by default `<iframe>` elements have a white background, which might be causing your issue (@bender2k14 in your case, I checked and this was indeed the issue). So simply adding a css rule to give the `<iframe>` element a `transparent` background should solve it.

**Comment by bender2k14** [comment]
> So simply adding a css rule to give the `<iframe>` element a `transparent` background should solve it.

And that CSS is precisely
```
iframe {
  background: transparent
}
```

**Comment by terroo** [comment]
Thanks for all the answers. I will close this issue
