### ISSUE TITLE
[Feature Suggestion]Add param "Delay"

### ISSUE THREAD

**Issue by Saafo** [utterance/utterances#294]
In some cases, the title of the page is dynamic added by javascript, in this case `utterances` will get the wrong title(i.e. the old title in html file). To add a param "Delay" would let utterances's `client.js` run after the javacript which changes the title.

**Comment by jdanyow** [comment]
you can insert the utterances script dynamically once you've determined the page title

https://github.com/utterance/utterances/issues/299#issuecomment-626125665
