### ISSUE TITLE
Axe scan shows Aria role error

### ISSUE THREAD

**Issue by dixonge** [utterance/utterances#304]
"Aria role tablist is not allowed for given element"

Not sure if fix is to remove the tablist role or change the element.

![Screen Shot 2020-04-26 at 7 12 12 AM](https://user-images.githubusercontent.com/1578506/80307224-4f5f3700-878d-11ea-9495-7516675b721d.png)

**Comment by jdanyow** [comment]
Good catch, it shouldn't be a `<nav>` element, it should be a `<div>`. Would you be willing to open a PR?
