### ISSUE TITLE
Migrating comments from WordPress

### ISSUE THREAD

**Issue by thomaslevesque** [utterance/utterances#305]
This project looks awesome, using Github issues for comments is a great idea! I'm considering switching from WordPress to a static website (perhaps using GitHub Pages), and I was wondering: is there a way to import WordPress comments using Utterances?

**Comment by szpak** [comment]
If you are asking about a way in general, WordPress gives you an ability to export your comments in parseable format, so using the GitHub API you could add the comments, enhancing their comments with metadata (e.g. time when it was placed or the commenter name).

In a case you are looking for a complete solution, I don't know any, but I also didn't migrate my comments, so maybe there is such as script and someone else will suggest it to you.

**Comment by thomaslevesque** [comment]
Hi @szpak, thanks for your quick answer. Yeah, I guess I could import them using the Github API. Not sure what it would look like, though... The comment would be posted by me, with just a note showing the original commenter name? Would Utterances be able to interpret this note and display the commenter name accordingly?

**Comment by thomaslevesque** [comment]
Oh! Feature idea: support for [YAML Front Matter](https://jekyllrb.com/docs/front-matter/) in comments. The Front Matter could contain metadata (e.g. original comment date and commenter name), and Utterances would read these metadata and display the correct date and name.

(Sorry, I haven't even used your project yet and already I'm suggesting new features... Maybe it's a bit premature!)

**Comment by szpak** [comment]
It seems that the comments are displayed as is using data from GH and it could be needed to display author and date as a part of the message itself.
However, I started using Utterances a week ago and I have just one comment, so I'm also just a beginner in that area. @jdanyow is a person who could answer credibly to your question.

**Comment by thomaslevesque** [comment]
I realize now that it wouldn't really make sense. In WordPress, a comment can be a reply to another comment, and appear as such. Github issues don't support that.

**Comment by techboyg5** [comment]
> 
> 
> I realize now that it wouldn't really make sense. In WordPress, a comment can be a reply to another comment, and appear as such. Github issues don't support that.

Yes they do. This is one!

**Comment by thomaslevesque** [comment]
> Yes they do. This is one!

Yes, but you just quoted my message. Your reply doesn't explicitly appear as a reply to mine, iow you didn't start a new "thread" off my message.

**Comment by techboyg5** [comment]
> 
> 
> > Yes they do. This is one!
> 
> Yes, but you just quoted my message. Your reply doesn't explicitly appear as a reply to mine, iow you didn't start a new "thread" off my message.

OK, thank you!

**Comment by aothms** [comment]
I've created a quick and dirty python script to import wordpress comments https://github.com/aothms/wordpress-to-utterances
