### ISSUE TITLE
Can't get it to work

### ISSUE THREAD

**Issue by kowalcj0** [utterance/utterances#308]
Hi,

I've installed `utterances` app on my repo but I can't get it to show up on my site.

Here's an example page https://kowalcj0.github.io/2020/03/22/listen-to-podcasts-in-mpd/ where comments sections should show up but instead it I'm getting this empty space:
![image](https://user-images.githubusercontent.com/910451/80849680-2963e780-8c10-11ea-87aa-8a8398c51fb8.png)

When I had a look at the request to `https://utteranc.es/utterances.html`
![image](https://user-images.githubusercontent.com/910451/80849565-8f9c3a80-8c0f-11ea-92d7-d38be96f2615.png)
I've noticed that it "hangs" indefinitely
![image](https://user-images.githubusercontent.com/910451/80849859-02f27c00-8c11-11ea-9107-ae51b2c1e461.png)

The Client config lgtm:
```html
<script src='https://utteranc.es/client.js'
  repo='kowalcjo/kowalcj0.github.io'
  issue-term='pathname'
  theme='github-light'
  crossorigin='anonymous'
  async>
```

I've also added `utterances.json` to root dir of the site: https://kowalcj0.github.io/utterances.json
But that didn't help. I'm bit lost now. 

ps. I'm using [hugo](https://gohugo.io/) with [minimo](https://github.com/MunifTanjim/minimo) theme to generate the site.

**Comment by congerh** [comment]
I think your repo is `kowalcj0` not `kowalcjo`.

**Comment by kowalcj0** [comment]
that was the silliest issue I've ever opened hahaha
thank you @congerh
