### ISSUE TITLE
[Feature Request] Option to toggle theme

### ISSUE THREAD

**Issue by samtay** [utterance/utterances#321]
I use the [chalk](https://samtay.github.io/) jekyll theme which has this cool light/dark toggle. It noticed playing around in the browser that if I modify the utterances iframe to just change the css link attribute between "github-light" and "github-dark", it triggers properly.

Of course since the iframe is hosted on a separate domain, I can't actually do this via javascript.

I'm sure this isn't a priority, but if it's easy to create this toggle, that would be awesome! Thanks.

**Comment by lights0123** [comment]
#170

**Comment by samtay** [comment]
Ah, thanks! :bow:
