### ISSUE TITLE
Utterances is collecting Data Via Google Analytics in comment widget

### ISSUE THREAD

**Issue by kaknut** [utterance/utterances#331]
Hie,
I was just trying it and looking around it's working and saw a strange thing. Me site is completely cookie free (I use privacy friendly analytics) but utterances sets Google analytics on the webpage which has cookie.

**Comment by congerh** [comment]
Utterances uses a cookie to store the GitHub API token. Only <https://utteranc.es> sets Google Analytics。You can check Utterances' [PRIVACY-POLICY](https://github.com/utterance/utterances/blob/master/PRIVACY-POLICY.md) for more details.

**Comment by kaknut** [comment]
Actually I saw that in the application storage. So if a user haven't visited the utterance site then there won't be a _ga cookie, right?

**Comment by kaknut** [comment]
I checked it in incognito mode, with no cache.
The page which loads it set's _ga and _gid. It's not good for privacy friendly sites like mine.

![ga](https://user-images.githubusercontent.com/33004850/83942280-cc131580-a80f-11ea-9f15-a2eb05889710.png)

**Comment by jerryc127** [comment]
https://github.com/utterance/utterances/blob/c97a0e9315fbaf0768cc7de6cedd235cc214466d/src/index.html#L89

**Comment by jdanyow** [comment]
only the home page (https://utteranc.es) uses google analytics. If you don't visit that page the cookie will not be set.
