### ISSUE TITLE
Auth Error when signing in to comment

### ISSUE THREAD

**Issue by donvito** [utterance/utterances#34]
I am encountering this error when I tried to sign in my blog. I also checked other sites using utterance and it is showing the same error.

<img width="984" alt="screenshot 2018-05-06 23 44 32" src="https://user-images.githubusercontent.com/890270/39675019-95f07668-5187-11e8-9ebe-dc8a36dc6e93.png">

**Comment by jdanyow** [comment]
yikes- checking... haven't changed anything lately

**Comment by jdanyow** [comment]
The node version specified in my package.json (8.1.0) was no longer available on Azure. To avoid this in the future I've changed the version spec to `8.x.x`.

**Comment by donvito** [comment]
Great, it works now! 👍 Thanks a lot! BTW, do you suggest hosting the script on my end to remove the dependency to your azure? How do I do that? I guess it will be useful to others as well. You also don't have to maintain in your server.

**Comment by donvito** [comment]
Thanks @jdanyow, a guide to self-hosting will be great. If I got some time, I'll blog about this, really cool!
