### ISSUE TITLE
blocked by privacy extension

### ISSUE THREAD

**Issue by azzamsa** [utterance/utterances#341]
Hi.

I just want to report this. In case anyone had the same problem of the comment didn't shows up.

Our next plan maybe to tell the popular privacy extension to whitelist us.

![image](https://user-images.githubusercontent.com/17734314/84839875-404b8580-b068-11ea-8069-cc309f9b20a3.png)

thank you for utterances.

**Comment by alexandru** [comment]
I need a fallback — I'd like to show an HTML message with a link to the created GitHub issue.

Any way to use utterance's API to build such a link and redirect to the corresponding issue?

This would be cool to have for browsers having JavaScript disabled too.

**Comment by alexandru** [comment]
@azzamsa why was this issue closed? Is it resolved?

Looking at [privacybadger#2640](https://github.com/EFForg/privacybadger/issues/2640), I don't think it is.

**Comment by azzamsa** [comment]
No response from a maintaner for such a long period of time.

And this can be solved in our side.

---

Should I re-open this issue?

**Comment by alexandru** [comment]
> And this can be solved in our side.

Any tips? Are you self-hosting it?
