### ISSUE TITLE
Redirects to 0.0.0.0 when trying to login through github

### ISSUE THREAD

**Issue by Uzay-G** [utterance/utterances#342]
For example, on this [page](http://uzpg.me/tech/2019/12/28/projects-and-learning-in-2019.html), signing in redirects to 0.0.0.0 instead of logging in the user. 

The code i used for utterances is here: https://github.com/Uzay-G/portfolio/blob/master/_layouts/post.html

Thanks for your help!

**Comment by congerh** [comment]
Utterances will use canonical URL if you set it.
See: <https://github.com/utterance/utterances/blob/094ced65e4dbfb0d4393b3190746931140919acd/src/client.ts#L35-L36>
You should fix the URL in `<link rel="canonical">` you set.

**Comment by Uzay-G** [comment]
Thanks! that works.
