### ISSUE TITLE
[Feature request] Add guest commenting support

### ISSUE THREAD

**Issue by forgenst** [utterance/utterances#357]
Hi,
 I quite like utterances commenting system and am currently using it. Is it possible if you could add guest commenting support, for example the @utterances-bot posting the comment in Issues on GitHub?

**Comment by kaknut** [comment]
Not possible mate. One needs to login to GitHub to comment. Even Utteranc.es Bot is a user and it still needs to login

**Comment by forgenst** [comment]
Good point. Yes, it wouldn't be possible.
