### ISSUE TITLE
It supports re-init the comments without reload the script ?

### ISSUE THREAD

**Issue by jerryc127** [utterance/utterances#359]
I want to use the comment plugin in SPA Website/Pjax Website.
It supports re-init the comments without reload the script ?

**Comment by bender2k14** [comment]
Can you give an example of how it would work to re-init the comments without reloading the script?

**Comment by jerryc127** [comment]
Use the pjax (https://github.com/MoOx/pjax) 
> Pjax loads pages using AJAX and updates the browser's current URL using pushState() without reloading your page's layout or any resources (JS, CSS), giving a fast page load.

Look like the disqus , it provide the reset function to call ,so we don't need to reload the script and just call the reset when you switch to another page
![image](https://user-images.githubusercontent.com/16351105/87783560-4ac78d80-c867-11ea-83ab-6f6537977fef.png)

so i want to know that the utterances supports re-initializing the comments without reload the script ?

**Comment by abbychau** [comment]
i need it too.
