### ISSUE TITLE
Add instructions for CSP

### ISSUE THREAD

**Issue by davidsneighbour** [utterance/utterances#371]
Installing utteranc.es on my blog led to some updates to my content security policy. Required are:

- script-src utteranc.es
- iframe-src utteranc.es

This should be reflected in the installation instructions.

**Comment by techboyg5** [comment]
Utterances's focus is on static websites. The most popular source for static websites is GitHub Pages. GitHub Pages doesn't support setting HTTP headers like `Content-Security-Policy`. Even `X-Frame-Options` isn't settable.

**Comment by davidsneighbour** [comment]
My website is done with [Hugo](https://gohugo.io). It works well and CSPs are allowed there. Static websites are possible on every single webserver system. I wouldn't constrict knowledge just because Github does not allow headers in it's hosted sites.

**Comment by AzrizHaziq** [comment]
should be: 
```
script-src utteranc.es
frame-src utteranc.es
```

no i in `iframe-src`
https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy/frame-src
