### ISSUE TITLE
How to solve the invalid repo problem

### ISSUE THREAD

**Issue by rscharfer** [utterance/utterances#394]
Hello,

I have **utterances** installed in my GitHub account, and it has access to the repository I want it to have access to: **rscharfer/myblog**. 

This is the script I am using in my app. 
```javascript
<script
          src="https://utteranc.es/client.js"
          repo="https://github.com/rscharfer/myblog"
          issue-term="pathname"
          theme="github-light"
          crossOrigin="anonymous"
          async
        ></script>
```

For some reason, I am getting the error `Uncaught Error: Invalid Repo`.  Does anyone have an ideas?

**Comment by JokerQyou** [comment]
You don't include the full repo URL. Just `username/reponame` would work. There is a form to generate the script for you at [the official site](https://utteranc.es/), you should start there.

**Comment by rscharfer** [comment]
Thank you!!

**Comment by brycewray** [comment]
> You don't include the full repo URL. Just `username/reponame` would work. There is a form to generate the script for you at [the official site](https://utteranc.es/), you should start there.

True, but it doesn't spell out — as you did — that it should be in that format. Thanks for making it clear; I was having the same problem as @rscharfer and was glad to see the answer here.
