### ISSUE TITLE
Failed to load resource: the server responded with a status of 401 ()

### ISSUE THREAD

**Issue by huydhoang** [utterance/utterances#397]
I inserted utterances in my blog and it is working. But I got this 401 error in Chrome console.
`POST https://api.utteranc.es/token 401`

These are the lines where I got error, specifically this function `r.apply(this, arguments);`
`Failed to load resource: the server responded with a status of 401 ()`

Does anybody know why? Does this affect commenting functionality in any way?

```javascript
        "function" == typeof fetch && (fetch = e(fetch, (r = fetch,
        function(t, e) {
            var n = s(e)
              , o = r.apply(this, arguments);
            if (n) {
                function u(t) {
                    c({
                        requestID: n,
                        statusCode: t && t.status
                    })
                }
                o.then(u).catch(u)
            }
            return o
        }
        )));
```

**Comment by rscharfer** [comment]
Is this only in incognito?

**Comment by rscharfer** [comment]
Actually, if you delete the cookies in normal mode, you will see the issue as well.

**Comment by brettinternet** [comment]
This appears to occur when the visiting user is not logged in. When I simply logged into GitHub through the script's UI, HTTP error should go away.

**Comment by jdanyow** [comment]
This is an expected status/response. The client does a POST to /token to retrieve the user's credentials/signed-in status. If the user is not signed in the service responds with a 401. Maybe I should make this a `204 no content` to avoid confusion.

**Comment by zsdycs** [comment]
401 Unauthorized: The user did not provide authentication credentials, or was not authenticated.

Reference: https://developer.mozilla.org/zh-CN/docs/Web/HTTP/Status/401

There is no problem with the response status 401 and it is impossible to be more correct.
Sometimes wrong means right. If verification is performed without verification information, verification will naturally fail.

**Comment by huydhoang** [comment]
Thanks for the answers, guys! I think this can be closed.
