### ISSUE TITLE
Dynamic theme switching

### ISSUE THREAD

**Issue by mrsauravsahu** [utterance/utterances#401]
I'm currently using utterances to add comments to my site. Sample is - https://mrsauravsahu.github.io/blog/39/ I have a theme toggle button in my navbar which allows to switch between light and dark themes. However, utterances loads directly when the page loads, so it does not respect the change in the theme attribute. 

Is there a way to dynamically switch themes?

**Comment by tmshkr** [comment]
You can dispatch a custom event on theme change, and then handle it with a function that will load the script again with the new theme.

https://developer.mozilla.org/en-US/docs/Web/Guide/Events/Creating_and_triggering_events

**Comment by mrsauravsahu** [comment]
Thanks @tmshkr 
Worked great.
Closing this.

**Comment by tmshkr** [comment]
Happy to help @mrsauravsahu 

It would be ideal if the theme could be changed without having to reload the script. There seems to be a [way to change the theme](https://github.com/utterance/utterances/blob/c1897f226dfa15b27f7950da27747b8996837b22/src/theme.ts#L10) without reloading the script by using `postMessage`.

For example, if you execute the following code in your browser console, it should change the theme of the comments to dark:
```
document.querySelector("iframe.utterances-frame").contentWindow.postMessage({type: "set-theme", theme: "github-dark"});
```
But it only seems to work on [utteranc.es](https://utteranc.es/) or the utterances local dev environment. It doesn't seem to work on other sites.

**Comment by mrsauravsahu** [comment]
I can give it a try.

**Comment by tmshkr** [comment]
Ah, the `targetOrigin` needs to be specified. This works:
```
document.querySelector("iframe.utterances-frame").contentWindow.postMessage({type: "set-theme", theme: "github-dark"}, "https://utteranc.es/");
```

**Comment by mrsauravsahu** [comment]
Oh that makes sense. There is a check on the origin

**Comment by mrsauravsahu** [comment]
Works great! Thanks @tmshkr 
https://mrsauravsahu.github.io/blog/39/

**Comment by transitive-bullshit** [comment]
That worked for me -- thanks @tmshkr
