### ISSUE TITLE
Create issue with just the post title

### ISSUE THREAD

**Issue by IsaacWoods** [utterance/utterances#41]
Specifying `issue-term="title"` gives both the title of the post and the whole blog, which for me is something like `You're up and running! – Isaac Woods – 17 year-old student, building low-level stuff in Rust`, which is really long as an issue name. Could we maybe have a `issue-term="posttitle"` or something to just use the title of the post?

**Comment by jdanyow** [comment]
The trick is coming up with a reliable way for utterances determine the post's title. I'm thinking we could add a new option called ***Issue title contains the page's [open graph](http://ogp.me/) title***.  When this option is selected utterances would look for a `<meta property="og:title" content="... the title ..." />` tag in your post's html and use the value of the content attribute as the github issue title. Would that work for you? If you could share the url of your blog I could take a look and confirm that will work.

**Comment by IsaacWoods** [comment]
Sounds great! I don't have any posts published to check, but Jekyll does seem to correctly emit the tag:
```
{% if page.title %}
<meta property="og:title" content="{{ page.title }}" />
{% endif %}
```

**Comment by jdanyow** [comment]
can you confirm the value is different than what it's putting in the `<title>...</title>` element?  (I want to be sure this will fix the issue).

**Comment by IsaacWoods** [comment]
It is:
```
<title>{% if page.title %}{{ page.title }} – {% endif %}{{ site.name }} – {{ site.description }}</title>
```
