### ISSUE TITLE
[feature requests] 

### ISSUE THREAD

**Issue by Galaxy-Coding** [utterance/utterances#410]
I have 2 feature requests. 
1. The textarea to make a comment should be all the way at the top, so users don't have to scroll down a wall of comments to submit their comment
2. I wish there was a custom way to enable utterances. There is an attribute called custom-title="enter-title-here". Utterances will search for an issue whose title contains the custom-title attribute. If a matching issue is not found, Utterances will automatically create one the first time someone comments on your post. The code would look like this:
`<script src="https://utteranc.es/client.js"
        repo="[ENTER REPO HERE]"
        issue-term="custom-title"
        custom-title="random-title"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>`
Please consider adding this feature as this would be very helpful for me and probably many other people using utterances. Than you very much! :)

**Comment by jdanyow** [comment]
hi @Galaxy-Coding the first item is requested in #182 

I think the second item is already implemented as the `Issue title contains specific term` option:
![issue title contains specific term](https://user-images.githubusercontent.com/1306747/98448743-53c4bf00-20e3-11eb-919a-b13321d3b0d8.png)
