### ISSUE TITLE
HTTP/2 403 Forbidden when posting comment

### ISSUE THREAD

**Issue by Aimeedeer** [utterance/utterances#418]
I can log in with GitHub, but it encounters a 403 issue when I submitted it.
The error message is:

```
POST https://api.utteranc.es/repos/Aimeedeer/test-utterances-bot/issues [HTTP/2 403 Forbidden 570ms]
```
The Response Payload also shows a message, but I have a verified email:
```
{"message":"At least one email address must be verified to do that.","documentation_url":"https://docs.github.com/articles/adding-an-email-address-to-your-github-account"}
```

My testing repo is:
https://github.com/Aimeedeer/test-utterances-bot

And the published site:
https://aimeedeer.github.io/test-utterances-bot/

**Comment by jdanyow** [comment]
this is fixed, thanks for reporting
