### ISSUE TITLE
[Feature request] Support a Mastodon backend for comments

### ISSUE THREAD

**Issue by augusto-herrmann** [utterance/utterances#419]
Many people are using [Mastodon](https://github.com/tootsuite/mastodon), which is a free and open source, decentralized, open protocol microblogging social network.

Utterances could implement support for Mastodon in a similar way that is done with Github issues. The page owner could associate a specific mastodon post to the page, so that any replies to it in the Fediverse (the decentralized web of microblogging messages) to that post would show up as comments.

**Comment by jdanyow** [comment]
sounds cool- I do not plan to implement this but it could make a good fork!
