### ISSUE TITLE
Change Sign-in button to make very clear it is github oauth login

### ISSUE THREAD

**Issue by sheldonhull** [utterance/utterances#435]
Realized when interacting with someone that they didn't realize the comments were powered by GitHub issues. Would be great if the login button could have minor tweaks to make it very clear it was GitHub auth. This might increase engagement from folks, rather than them thinking they have to sign-up for another system.

Example of how this could look: 

- [GitHub OAuth Buttons](https://github.com/oAuth-Buttons/oAuth-Buttons)
- [My favorite - very easy to see immediate](https://blog.oauth.io/how-to-add-github-social-login-button)

The code sample the second link provided was: 

```html
<a id="github-button" class="btn btn-block btn-social btn-github">
  <i class="fa fa-github"></i> Sign in with Github
</a>
```

**Comment by jdanyow** [comment]
I like this idea.

**Comment by jdanyow** [comment]
#479

**Comment by sheldonhull** [comment]
Looks great, thanks for doing this 💯
