### ISSUE TITLE
White background box appeared for my comment section 

### ISSUE THREAD

**Issue by Aizera** [utterance/utterances#438]
Hello,
I'm using dark theme, windows 10, on chrome. I haven't checked my blog in a while so I am not sure exactly how it broke, but the white box was not present in my last build around 2 months ago. 
![image](https://user-images.githubusercontent.com/33512904/102242679-2bcd3600-3eaf-11eb-80f3-e1ce88dd742c.png)

**Comment by jdanyow** [comment]
url?

**Comment by Aizera** [comment]
https://aizera.page/post/connie-say-myanmar-lyrics/

I linked the latest post but it happens on every post so far

**Comment by jdanyow** [comment]
This was interesting... I *think* this is a browser bug, we'll see what they say...
https://crbug.com/1175484

Removing the color-scheme meta element and the :root { color-scheme: ...  } property from your stylesheet resolves the issue but I doubt you want to do that.

**Comment by jdanyow** [comment]
here's the response:

>This is per spec where the used color-scheme of the iframe element and the iframe document's root element differ.
>If you add style="color-scheme:light" on the iframe element it becomes transparent.

I've shipped the fix, looks like it's working on your site now. Thanks for reporting this.
