### ISSUE TITLE
How can I use utterances on a page with a non-white background?

### ISSUE THREAD

**Issue by m90** [utterance/utterances#44]
Utterances currently forces the iframe that is being injected to have a `white` background color, which makes it possibly not-so-pretty on pages that do not share the plain white background:

![image](https://user-images.githubusercontent.com/1662740/42083399-15fa9b2c-7b8b-11e8-883a-976a2aae4ccd.png)

It would be relatively trivial to make `body` have `background-color: transparent` and `.comment` have `background-color: white` (as seen [here](https://github.com/utterance/utterances/compare/master...m90:transparent?expand=1)), but I would assume this is an unwanted breaking change for others.

Are there established ways of doing this yet? In case not, would you be open to adding some customization options to the script? Maybe something like adding `data-background-color` to the script tag itself?

**Comment by jdanyow** [comment]
Sounds good to me. Let's start with making the background transparent.
