### ISSUE TITLE
404 error occur when I click utterance comment button

### ISSUE THREAD

**Issue by hanseul-lee** [utterance/utterances#443]
I want to set utterence on my blog

I did three things like below

1.themes/tranquilpeak/layout/_partial/post/utterances.ejs
```
<script src="https://utteranc.es/client.js"
        repo="{userid}/blog-comments"
        issue-term="title"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

2. themes/tranquilpeak/_config.yml
```
# ---------------
# Comment systems
# ---------------
...
utterances:
    enable: true
...
```

3. themes/tranquilpeak/layout/_partial/post.ejs
```
<article class="post">
    ...
    <% if (post.comments) { %>
        ...
        <% } else if (theme.utterances.enable) { %>
            <%- partial('post/utterances') %>
        <% } %>
    <% } %>
...
```

Aftert that, I can see the the utterence comment layout,
but when I clicked the comment button, 404 error occurred
https://hanseul-lee.github.io/  here is my blog link

I don't know how to solve this.
So could you please help me?

**Comment by GrahamSH-LLK** [comment]
It seems to de-capitalize links.

**Comment by hanseul-lee** [comment]
@GrahamSH-LLK 
Counld you tell me more specifically? I don't know where to de-capitalize

**Comment by GrahamSH-LLK** [comment]
Sorry, what I meant is that when utterances redirects, the link has been decapitalized. The blog 404s because the link is wrong, it's not capitalized.

**Comment by hanseul-lee** [comment]
Then how can i figure it out about ? Am i doing somthing wrong when changing the code like above..?

**Comment by Aroong** [comment]
안녕하세요 저도 비슷한 이슈로 하루종일 찾다가 해결했는데 utterances 코멘트 버튼 눌렀을때 redirect 되는 주소가 전부 소문자네요 (예 : https://hanseul-lee.github.io/2021/01/05/react-13/)  

그런데 실제 주소는 => React-13 대문자가 포함되있다보니 404뜨는거 같습니다. 
컨텐츠 명을 소문자로 바꾸면 될거같네요... 그럼 대문자는 못쓰는건가;;;

**Comment by jdanyow** [comment]
Utterances uses the canonical url of your blog post when available.
There appears to be an issue with canonical urls on your blog. This page: https://hanseul-lee.github.io/2021/01/05/React-13/
Has the following canonical url:
```html
<link rel="canonical" href="https://hanseul-lee.github.io/2021/01/05/react-13/">
```
