### ISSUE TITLE
uttrances box appear for a moment and disappear.

### ISSUE THREAD

**Issue by bmh8993** [utterance/utterances#445]
https://user-images.githubusercontent.com/45564139/103133718-590bb680-46ef-11eb-97fc-0648c0261746.mov

Hi, I use utterances to my blog that It is hosted on netlify.

but like in the video above, uttrances box appear for a moment and disappear.

This video is a recording of the moments I refresh.

Theme is https://github.com/hasura/gatsby-gitbook-starter

**Comment by SpheeresX** [comment]
Could you send a link to your blog?

**Comment by bmh8993** [comment]
hi

hmm.. I removed my blog...
