### ISSUE TITLE
White space at left of comments area, with nothing but profile pictures

### ISSUE THREAD

**Issue by nyanpasu64** [utterance/utterances#457]
The comments section has around 60 pixels to the left of the actual comments, which is empty except for profile pictures. This causes the comments section to appear misaligned with the page body. Is there a workaround to disable or move the pictures?

![firefox_2tSGKKVKPL](https://user-images.githubusercontent.com/913957/103456679-5ee43780-4cad-11eb-809f-3a5590ef2d9d.png)

I tried using CSS to add a negative margin to the .utterances element, but it would end up off-screen when I shrank my window.

**Comment by jdanyow** [comment]
@nyanpasu64 it's intentional, to match github's issue comment timeline.

**Comment by nyanpasu64** [comment]
The difference is that GitHub's issue comment timeline isn't aligned with a centered blog post (neither the original report nor replies are centered without avatars), and has an extra side bar on the right, so the layout doesn't look out-of-place. However in my blog, the horizontally aligned post body just above the comments makes the comment bodies look noticeably offset.

**Comment by TysonMN** [comment]
Can you include a screenshot?

**Comment by nyanpasu64** [comment]
I already had a screenshot in my original post, but I just edited it to make it more obvious. If you want a wider picture, you can visit my blog at https://nyanpasu64.github.io/blog/an-unsafe-tour-of-rust-s-send-and-sync/.

I've taken a new screenshot that includes more of the white space to the left/right of the blog and comments:

![image](https://user-images.githubusercontent.com/913957/107145763-a1c2ac00-68f8-11eb-824a-6ab384b5a829.png)
