### ISSUE TITLE
Q: Is it possible to left align the comment section?

### ISSUE THREAD

**Issue by introspectionism** [utterance/utterances#460]
Is is possible to have the comment section left aligned?

If, for example, there is a way to inject `float:left;` so the style attribute to the `<div class="utterances" ...>`, it would work. To achieve something like this:
`<div class="utterances" style="height: 269px; float:left;">`

**Comment by introspectionism** [comment]
Just realised that I can fix this by adding this to my style sheet:
```
.utterances {
    float: left;
}
```
Not sure if that will mess up anything. It seems to be working though.

**Comment by TysonMN** [comment]
Sounds like you were able to solve your own problem.  Great!

Would you mind closing this issue?
