### ISSUE TITLE
widget doesn't appear on jekyll + github-pages

### ISSUE THREAD

**Issue by marnec** [utterance/utterances#461]
I'm building a github-pages webiste with jekyll. The repository uses the docs/ folder on the master branch.
This is the address of the website: https://marnec.github.io/ML/
This is the address of the repo: https://github.com/marnec/ML
The utterances app is installed and configured for my repository and the issues are activated.

I followed all the instructions I could find but the comments widget never appear in the pages were the code snipped is.

**_includes/comments.html**
```
{% if page.comments %}

    <h2>Comments</h2>

    <script src="https://utteranc.es/client.js"
            repo="https://github.com/marnec/ML"
            issue-term="pathname"
            label="comment"
            theme="github-light"
            crossorigin="anonymous"
            async>
    </script>

{% endif %}
```

**_layouts/default.html**
```
[...]
  <body>
    {%- include header.html -%}
    <main class="page-content" aria-label="Content">
      <div class="wrapper">
        {{ content }}
        {%- include comments.html -%}
      </div>

    </main>
    {%- include footer.html -%}
  </body>
[...]
```

**webpage**
See this page for example. At the bottom you can see the `<h2>Comments</h2>` element but no widget.
https://marnec.github.io/ML/ML2/

I don't understand what I'm doing wrong

**Comment by GrahamSH-LLK** [comment]
``repo="https://github.com/marnec/ML"`` shouldn't include https://github.com/

**Comment by marnec** [comment]
thanks a lot! Sorry it was my bad, but I'd like to give just a little suggestion. In the [snippet building tool](https://utteranc.es/) maybe you could trim the `https://github.com/` part in case someone like didn't read with too much attention. 

Thanks again
