### ISSUE TITLE
Separate SITES.md from this repository

### ISSUE THREAD

**Issue by ouuan** [utterance/utterances#464]
Now the commit log and the pull requests are full of "Update SITES.md". We can view the commit log of the `src` directory, though.

I think it will be better if the SITES.md is in a different repository.

(Personally, I don't think it makes sense to allow everyone to add their site to a list which already consists of 151 items. The 3.7k stars speak well, and we only need some famous sites on the list. But that's another problem.)

**Comment by jdanyow** [comment]
Agreed, it was helpful early on so folks could see examples but it's gotten out of hand at this point.

**Comment by nschonni** [comment]
Maybe instead of moving/recreating the SITES.md, the suggestion for authors would be to use a repo tag like https://github.com/topics/utterances
