### ISSUE TITLE
Utterances forum

### ISSUE THREAD

**Issue by markknol** [utterance/utterances#465]
Would be great if Github's "discussions" (which is a forum) could also be embedded like utterances does for issues.

**Comment by phil-opp** [comment]
This was already suggested in #324. I fully agree that support for GitHub discussions would be great.

Unfortunately, it seems like GitHub [doesn't provide API access to discussions yet](https://stackoverflow.com/questions/65166895/how-to-query-data-from-github-discussions-using-githubs-graphql-api).

**Comment by abdusco** [comment]
A private API for the discussions is now available.

https://github.com/github/feedback/discussions/43#discussioncomment-339955

https://gist.github.com/smashwilson/311e1487ddb40a455fc54d294cc63ad4
