### ISSUE TITLE
How to delete/hide unwanted comments?

### ISSUE THREAD

**Issue by cannorin** [utterance/utterances#48]
Though I hid comments on the corresponding GitHub Issue page (because they are abusive), utterances still continues to show those comments on my blog post. 

Since the comments are posted with utterances, I (owner) cannot just delete them (the ... button does not appear in the comments posted with third-party apps).

How can I remove them from the blog post? Thanks in advance!

**Update:** I contacted to GitHub and thankfully they deleted the comments that were a problem. Though I think it is better to hide comments on blog posts that are hidden in the corresponding issue pages (is it possible?).

**Comment by jdanyow** [comment]
@cannorin I'll look into this- thanks for reporting.

**Comment by cannorin** [comment]
**Update 2:** GitHub said the "..." button not appearing was a bug and it now seems got fixed.

**Comment by jdanyow** [comment]
Looked into this. Currently the github api doesn't each comment's hidden status. You'll still need to use the "..." to delete the comment. Hiding it won't prevent it from appearing in utterances 😞

**Comment by cannorin** [comment]
Thank you anyway 😢
