### ISSUE TITLE
dark theme?

### ISSUE THREAD

**Issue by herohamp** [utterance/utterances#49]
My site uses a dark theme, how can I style utterances to be dark?

**Comment by herohamp** [comment]
Possibly based on https://github.com/StylishThemes/Github-Dark

**Comment by herohamp** [comment]
I'm thinking of piping the service through nginx, and add an css stylesheet, but the kinda defeats the no server aspect of it

**Comment by JokerQyou** [comment]
I think currently there is no way to style utterances elements because it uses `iframe`?
Would it be suitable to allow loading custom CSS file in the iframe so we could apply custom styles?

Say we add an attribute `custom-css` to the script:
```js
<script src="https://utteranc.es/client.js"
        repo="[ENTER REPO HERE]"
        issue-term="url"
        crossorigin="anonymous"
        custom-css="https://example.com/my/custom/styles.css"
        async>
</script>
```

And utterances load this CSS file inside the `iframe`.

**Comment by benharri** [comment]
Dark mode is greatly needed. I've tried including some of the generated styles from [darkreader](https://github.com/darkreader/darkreader) and they don't apply properly inside the iframe.

**Comment by tarampampam** [comment]
@jdanyow This is most important feature for me, dude
