### ISSUE TITLE
Can the theme be changed on the fly?

### ISSUE THREAD

**Issue by Miigon** [utterance/utterances#491]
So I am using utterances for my blog, which has a switch to toggle between light and dark mode.

I wonder if there's any way for utterances to switch theme on the fly (maybe with some css or javascript?) so the comment section can always match the whole site's theme.

**Comment by brennerm** [comment]
Seems like a duplicate of #427 to me.

**Comment by Miigon** [comment]
Yes, it is. Thanks.

The solutions in #427 all feels like hacks though. Still hope that utterances can support this out of the box.

Anyway, closing this issue for now.
