### ISSUE TITLE
Fixed maximum width of timeline

### ISSUE THREAD

**Issue by PhilipTrauner** [utterance/utterances#50]
First of all: Thanks for Utterances. Its exactly what I need for my blog. :+1: 

There is just one single line of code that's bugging me a little bit:
https://github.com/utterance/utterances/blob/7c518a05a4522c03d3841ec16d7ec8d2f3081eb0/src/_timeline.scss#L2

It would be great if the width css rule of the `timeline` class could be unset with an additional script tag parameter (or be set to `100%` by default). 

With kind regards,
Philip Trauner

**Comment by jdanyow** [comment]
hi @PhilipTrauner - the 760px value was chosen to match github's style. If you open the dev tools while on this page and execute the following code you should see 760px:
```js
window.getComputedStyle(document.querySelector('.discussion-timeline')).width
```

I think this width was chosen to [optimize cpl for reading](https://graphicdesign.stackexchange.com/a/13730).

**Comment by PhilipTrauner** [comment]
I get that replicating the GitHub style is what you are going for, but wouldn't it make more sense to just set the `max-width` of the timeline to 100% and then let the user set their own desired width in the `.utterances` class? The default width could still be set to `760px` this way, while allowing the utterances timeline to scale properly when paired with content that makes use of more horizontal screen real estate.
