### ISSUE TITLE
If I close the Issue, do the comments get deleted?

### ISSUE THREAD

**Issue by 1RedOne** [utterance/utterances#510]
I like seeing no open issues on my repos, so if I close the issue, does the comments go away?

**Comment by TysonMN** [comment]
No

**Comment by AntoineSoetewey** [comment]
And people can still comment after having closed the issue?

**Comment by TysonMN** [comment]
Yes

**Comment by CyrusYip** [comment]
> I like seeing no open issues on my repos, so if I close the issue, does the comments go away?

You can use a separate repo to store comments instead of putting issues and comments in the same repo.

**Comment by koraylinux** [comment]
Should we seperate the labels with comma?

Such this: label="comment, issue, bug"

**Comment by jdanyow** [comment]
Closing the issue will not remove or disable commenting. You can disable commenting by locking the issue. To delete comments, delete them individually via the github ui or delete the entire issue using the github ui.
