### ISSUE TITLE
Load client.js from https://utteranc.es is a mandatory?

### ISSUE THREAD

**Issue by gpillot** [utterance/utterances#517]
I don't feel safe to load an external java script to my blog. (I need to add CSP rules in order to use utterances).

Is it possible to use the tool in standalone? It is not enough to just download client.js in my website.

**Comment by jdanyow** [comment]
That's a valid concern. The script is necessary because the utteranc.es iframe posts messages to the host page instructing it to resize the iframe.
https://stackoverflow.com/q/9975810/725866

**Comment by gpillot** [comment]
I download client.js, utterances.html, utterances.3c7bd773.js and utterances.css. I changed URL path in the code and it seems it can be working. But the problem is about CORS api.utteranc.es. The token is sent from my website to api.utteranc.es and of course it is blocked by the browser. Do you think it is possible to fix this?
