### ISSUE TITLE
Implement GitHub Discussions support with/instead of GitHub Issues support

### ISSUE THREAD

**Issue by Serpentiel** [utterance/utterances#530]
Recently GitHub has introduced a new feature which is [GitHub Discussions](https://docs.github.com/en/discussions) and it appears to me that it is a viable alternative for current plugin algorithm, which works via GitHub Issues. I suggest to provide support for it because it might prevent Issues section cluttering.

**Comment by nschonni** [comment]
Duplicate of https://github.com/utterance/utterances/issues/324
