### ISSUE TITLE
API server responds with 403 while creating issue.

### ISSUE THREAD

**Issue by cubarco** [utterance/utterances#536]
While I was trying to make a comment on a page without issue created, the API server failed on create the issue and respond with 403 instead.

Request in cURL:
```shell
curl 'https://api.utteranc.es/repos/cubarco/cubarco.github.io/issues' \
  -H 'authority: api.utteranc.es' \
  -H 'pragma: no-cache' \
  -H 'cache-control: no-cache' \
  -H 'sec-ch-ua: " Not;A Brand";v="99", "Google Chrome";v="91", "Chromium";v="91"' \
  -H 'accept: application/vnd.github.squirrel-girl-preview' \
  -H 'authorization: token TOKEN_OMITTED' \
  -H 'sec-ch-ua-mobile: ?0' \
  -H 'user-agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_6) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.77 Safari/537.36' \
  -H 'content-type: text/plain;charset=UTF-8' \
  -H 'origin: https://utteranc.es' \
  -H 'sec-fetch-site: same-site' \
  -H 'sec-fetch-mode: cors' \
  -H 'sec-fetch-dest: empty' \
  -H 'referer: https://utteranc.es/' \
  -H 'accept-language: zh-CN,zh;q=0.9,en-US;q=0.8,en;q=0.7,hr;q=0.6,zh-TW;q=0.5,ja;q=0.4' \
  --data-raw '{"title":"2018/07/writeup-ctfzone/","body":"# Writeup: CTFZone 2018 Quals - /home/cubl\n\n\n\n[https://cubl.in/2018/07/writeup-ctfzone/](https://cubl.in/2018/07/writeup-ctfzone/)"}' \
  --compressed
```

Response:
status code: 403
```
{"message":"At least one email address must be verified to do that.","documentation_url":"https://docs.github.com/articles/adding-an-email-address-to-your-github-account"}
```

**Comment by termoxin** [comment]
Hey! Yeah, I have 403 Error as well

**Comment by termoxin** [comment]
@cubarco there's something wrong with creating issues

If you create an issue manually, it works fine

**Comment by psgandalf** [comment]
I have the same problem. I have an verified email address. Is it the other way around and that utterances bot doesn't have an verified email address?

**Comment by alohaia** [comment]
It seems that I'm not alone.
![2021-05-30 19-16-12](https://user-images.githubusercontent.com/36324537/120102031-b6fb6900-c17b-11eb-88be-8ea511266173.png)

**Comment by alohaia** [comment]
> @cubarco there's something wrong with creating issues
> 
> If you create an issue manually, it works fine

You're right. I tried creating issues manually, and it works fine as well.

**Comment by wanghsinche** [comment]
met 403 too, please help to fix it

**Comment by Eduardo-H** [comment]
I'm having the same issue here. 😕

**Comment by hariombalhara** [comment]
Same issue for me as well.

**Comment by thr3athunt3r** [comment]
Just started to use utterances today, been debugging for hours then i see this issue...

**Comment by adyanth** [comment]
Just installed this today, and it is failing :(
Created the issue manually and added the first comment, and everything is fine.
@jdanyow Thoughts? Also, is there a way to host the cloudflare worker ourselves?

**Comment by jdanyow** [comment]
@cubarco are you still able to reproduce? It's working for me.

**Comment by jdanyow** [comment]
bot account is creating issues: https://github.com/issues?q=is%3Aissue+author%3Autterances-bot
