### ISSUE TITLE
Issues not created 

### ISSUE THREAD

**Issue by BulletTech2021** [utterance/utterances#537]
# Description

I have followed the [instructions ](https://utteranc.es/)to configure the app. The[ comments module](https://bullettech.github.io/BulletTech/blogs/2021-05-30-Test/) display already and users can log in while the issues are not created after submitting the comments.

# Template
This is the [template ](https://github.com/BulletTech/BulletTech/blob/main/material/overrides/blogs.html)that sports a comment module.

# Error
There is no error in the console. I suspect that the repo name was not correct but it did not work out after I tried many ways. Please help troubleshoot. Thank you!

**Comment by fenbf** [comment]
same here!

on my website, I successfully installed the bot many months ago, but today I got reports that users cannot create their first comment under a new article.
They can add a comment to the existing discussion, but not the first under the article...

Can you help?

My article: https://www.cppstories.com/2021/05/talk-filter-elements/

**Comment by jdanyow** [comment]
Is the utterances application installed on the repository? https://github.com/apps/utterances

**Comment by jdanyow** [comment]
fixed- something was up with the bot account.
https://github.com/issues?q=is%3Aissue+author%3Autterances-bot

**Comment by BulletTech2021** [comment]
> fixed- something was up with the bot account.
> https://github.com/issues?q=is%3Aissue+author%3Autterances-bot

It works, thank you very much! wanna suggest an enhancement to **be compatible with the switch of light/dark mode**. 

Example: https://pawamoy.github.io/posts/migrate-disqus-comments-to-utterances-github/
