### ISSUE TITLE
Allow user to load CSS files on their own so they can easily change theme

### ISSUE THREAD

**Issue by deadcoder0904** [utterance/utterances#544]
I want to change light/dark theme based on user preferences.

Currently, it's cumbersome as one has to load 2 scripts & then delete like https://github.com/utterance/utterances/issues/427 or use `iframes` function `postMessage` & mount/unmount the component like https://github.com/utterance/utterances/issues/161#issuecomment-873431594

By allowing users to load their own CSS file, they can easily swap themes.

**Comment by laymonage** [comment]
This is duplicate of #367.

Side note and shameless plug (sorry!): I made a similar project that utilizes GitHub Discussions: [giscus](https://giscus.app). It has support for custom CSS files.

**Comment by deadcoder0904** [comment]
Alright, I'll close this one then. I've managed to [make it work](https://github.com/utterance/utterances/issues/161#issuecomment-874731552) for now using `iframes` function `postMessage`.

@laymonage nice name. it looks great but what are the differentiated features than `utterances` that would make me switch? u can add that to readme as well since it'll be the most common question.

I see 2 main differences:

1. discussions rather than issues
2. custom CSS

But when I load the new theme, I get a flash of white first, then the new theme. Check utterances how it loads the new theme directly.
