### ISSUE TITLE
Ignore anchors when using "Issue title contains page URL" mode5

### ISSUE THREAD

**Issue by phil-opp** [utterance/utterances#55]
I use autogenerated anchors for every heading on my site for a table of contents. When clicking such an anchor link the URL changes to `example.com#anchor-title`. When I now refresh the page (i.e hit F5), the comment section stays empty because utterances looks for an issue title with the correct `#anchor-title`. If I now post a comment a new issue is created for the same page.

To fix this, I would propose to just ignore any anchors when doing URL matching, or at least providing an option to do so. What do you think?

**Comment by jdanyow** [comment]
I agree, I think this is a bug. We should ignore both querystring/search and hash/anchor by default. Also need to normalize trailing backslash.

For example, this url in the address bar:
```
https://os.phil-opp.com/minimal-rust-kernel/?foo=bar&b#anchor
```
Should result in a search for issues whose title contains:
```
https://os.phil-opp.com/minimal-rust-kernel
```

Thoughts?

**Comment by phil-opp** [comment]
Sounds good to me! However, I think there are some sites that use the query string for determining which article to show (e.g. `?article_id=1234`).

Maybe we can use the rel=canonical link when present and default to ignoring query string/anchor else?

**Comment by phil-opp** [comment]
I know that I'm a bit late, but thanks for fixing this so quickly! It works without problems now.
