### ISSUE TITLE
Invalid Repo

### ISSUE THREAD

**Issue by sajrashid** [utterance/utterances#550]
Hi, 

I've used the form to generate the URL to my [repo](https://github.com/sajrashid/React-Dynamic-Json-Table/) 
The Utterances app is installed and has permissions
I've checked this closed [issue](https://github.com/utterance/utterances/issues/394) 

The script downloads to the client I can see an http 200 to utterances.es from fiddler

This is the browsers error message

**Uncaught Error: Invalid repo: "https://github.com/sajrashid/React-Dynamic-Json-Table/"
    at pa (utterances.3c7bd773.js:1)**

script generated from [uterances.es](https://utteranc.es/)

`<script src="https://utteranc.es/client.js"
        repo="https://github.com/sajrashid/React-Dynamic-Json-Table/"
        issue-term="pathname"
        theme="github-dark"
        crossorigin="anonymous"
        async>
</script>`

Can't see anything obvious, is there anything else I should be doing ?

Thank-you

**Comment by coder-lg** [comment]
Yoooo, don't put the repo link, put the repo like this:
`owner/repo`

**Comment by sajrashid** [comment]
hey, much appreciated fixed thanks
