### ISSUE TITLE
Is utteranc.es down?

### ISSUE THREAD

**Issue by alroniks** [utterance/utterances#555]
Hello, I found out that website, mentioned in configs and other places https://utteranc.es/ can not be open. 

I am wondering is it my local issue or website is broken?

**Comment by TysonMN** [comment]
It works for me

**Comment by acgaudette** [comment]
I had a similar issue, but it was due to a global cookies ban on the browser I was using at the time. when cookies are disabled, the widget doesn't render. check your console, see if anything is throwing from the utterances script?

**Comment by alroniks** [comment]
In Belarus it does not work, also checked with some people in the country. Seems IP in the blacklist of provides or maybe even the government. Seems I need to run own copy of the bot. So, closing.
