### ISSUE TITLE
2 different pages have the same comments

### ISSUE THREAD

**Issue by if2012** [utterance/utterances#56]
2 different pages have the same comments

- [https://if2012.github.io/post/my-first-post/](https://if2012.github.io/post/my-first-post/)

- [https://if2012.github.io/post/travis-basis/](https://if2012.github.io/post/travis-basis/)

there is only 1 issue [https://github.com/if2012/blog-comments/issues/1](https://github.com/if2012/blog-comments/issues/1) and both pages display it.

**Comment by jdanyow** [comment]
Doesn't look like you're using utterances.

**Comment by if2012** [comment]
@jdanyow it's good now
