### ISSUE TITLE
Issue with repo

### ISSUE THREAD

**Issue by teotenn** [utterance/utterances#572]
Hi, I cannot set up my repo <https://github.com/RWhiteDwarf/blog> As you can see it is mixed caps and small letters. I already tried both in the script but still the same error in JS: Uncaught Error: Invalid repo: "https://github.com/RWhiteDwarf/blog"

**Comment by laymonage** [comment]
You're supposed to type in `RWhiteDwarf/blog`, without `https://github.com/`.

**Comment by teotenn** [comment]
Thanks, it did change but now there is a different error in the console:

```
Failed to load resource: the server responded with a status of 422 ()

Uncaught (in promise) Error: Error fetching issue via search.
    at utterances.9ae412b8.js:1
    at async Promise.all (utteranc.es/index 0)
```

I already have granted access to the github app. My exact chunk of code looks like this:
```
<script src="https://utteranc.es/client.js"
        repo="RWhiteDwarf/blog"
        issue-term="title"
        label="Comment"
        theme="github-light"
        crossorigin="anonymous"
        async>
</script>
```

**Comment by teotenn** [comment]
Could it be related to the fact that my repo branch is named as `main` and the script works with `master`? - My repo is less than a week old and thus I'm using the new github standards.
