### ISSUE TITLE
Ability to comment without a github account

### ISSUE THREAD

**Issue by Daniellop1** [utterance/utterances#578]
I think it would be a good idea to have the option to put a comment without a github account

**Comment by taniarascia** [comment]
I don't.

**Comment by bdrelling** [comment]
@Daniellop1 how would you envision that working?

**Comment by ross-spencer** [comment]
Also skeptical, but understand the instinct. There seems to be a previous project that would allow anonymous posting to an issues repo: https://github.com/schneidmaster/gitreports.com but even the demo: https://gitreports.com/ doesn't work at the moment, so very inspiring. One could imagine if it worked it would be useful for the OP here.

**Comment by im-coder-lg** [comment]
But that might maybe increase spam comments, right?

**Comment by Daniellop1** [comment]
> But that might maybe increase spam comments, right?

That's not true because you can use for example Recaptcha

**Comment by Daniellop1** [comment]
> Also skeptical, but understand the instinct. There seems to be a previous project that would allow anonymous posting to an issues repo: https://github.com/schneidmaster/gitreports.com but even the demo: https://gitreports.com/ doesn't work at the moment, so very inspiring. One could imagine if it worked it would be useful for the OP here.

I've tried this one for a while and worked good

**Comment by Daniellop1** [comment]
I close this issue because we are not going to get to any point

**Comment by im-coder-lg** [comment]
> That's not true because you can use for example Recaptcha

Recaptcha is easy to solve, a robust system could be added tho
