### ISSUE TITLE
I can leave a comment as another person on my blog

### ISSUE THREAD

**Issue by emgoto** [utterance/utterances#580]
After a person comments on my site, I can then comment using their account on any post on my site. e.g. this is not my account, but I can leave a comment with it:

<img width="829" alt="Screen Shot 2022-01-02 at 4 19 02 pm" src="https://user-images.githubusercontent.com/33337378/147866995-afa66eb7-5d15-4bd3-b996-eb8d9da8aab0.png">

I'm not sure how this is possible.

* [My site](https://www.emgoto.com) is running with Gatsby, [here's the utterances code](https://github.com/emgoto/emgoto.com/blob/master/src/components/comments/index.js)
* I can do it on my normal browser (Firefox), but can't reproduce it if I open a new tab in incognito or try another browser

**Comment by vazaha-nl** [comment]
Same issue here... this is not good. I am logged in as myself but on my page https://vazaha.blog/en/9/php-frankenstein-arrays it looks like I am logged in as the commenter and my own comment (2nd one) is posted under his account.

**Comment by darrow-olykos** [comment]
yikes

**Comment by emgoto** [comment]
I'm not sure what's the best way to reach out to the owner - @jdanyow?

**Comment by jdanyow** [comment]
Hey folks- I saw this thread. I cannot reproduce the issue. Utterances doesn't store any credentials/tokens server side so I can't think of how it would be possible for you to sign in as another user. Have you been able to post a comment as another user? If so, can you link me to the comment on github?

Any errors in the console?

**Comment by emgoto** [comment]
^ Here's an example of me using someone else's account (sorry gjurd!)

**Comment by laymonage** [comment]
Here's my thoughts on this:

This part of the code,

https://github.com/utterance/utterances/blob/607b8ace059b8a726dea8a20541b1936a9c9ad88/src/client.ts#L37

Uses `location.search`, which might still contain the `utterances` session param. Even though you've removed it and called `history.replaceState` before:
https://github.com/utterance/utterances/blob/607b8ace059b8a726dea8a20541b1936a9c9ad88/src/client.ts#L8-L16

The iframe was still created with `location.search` as part of its `url` query param, which is used by utterances to link to the website in the issue starter post. So, if you look at @emgoto's issues, issues made by @utterances-bot has the `?utterances=` query param in the link to the website, which is the session ID. If you click the link, you'll use the session  of the user who triggered the issue creation.

You can probably fix this by making sure the `utterances` query param is removed before setting the value for `attrs.url`.

I came across a similar issue in https://github.com/giscus/giscus-component/issues/8.

**Comment by jdanyow** [comment]
fixed, all tokens revoked, thanks for reporting!

**Comment by thelmatorres4g-design** [comment]
test
