### ISSUE TITLE
How to solve this problem ?

### ISSUE THREAD

**Issue by terroo** [utterance/utterances#595]
Background iframe of the Utterances it's white

![captura-14-02-2022-22-45-19](https://user-images.githubusercontent.com/41500739/153977284-2055b15d-de3f-450f-8429-52e0a5bcd355.png)

**Comment by cometj03** [comment]
It looks like Github Dark theme. Why don't you change the theme to Github Light, for instance?
You can change theme through a parameter in the script tag.

**Comment by terroo** [comment]
Thanks, @cometj03 ! I will try to change the theme .
