### ISSUE TITLE
Utterances doesn't work on GitHub Pages

### ISSUE THREAD

**Issue by SimonYoungCN** [utterance/utterances#610]
I created my own blog by using Hugo and GitHub Pages yesterday, and it works well. Then I tried to add utterances as the comment system to my blog. But here came the problem: When in preview mode(https://localhost:1313), I can use the utterances to comment and it worked pretty well. 
![pic](https://user-images.githubusercontent.com/64118289/174758945-60f9a2e9-35da-4234-8460-15e57d8f1b20.png)
However, in the normal mode (after I send the update to GitHub Pages to reload my blog and check it via url) I could't even sign in with GitHub and when I clicked the sign in button, the page turned to nothing but this:
![pic2](https://user-images.githubusercontent.com/64118289/174759408-c0d9fbb8-240d-4bbb-92e2-da637a463779.png)
It says the pages can not be found and my site is not safe (not in the first picture). I'm pretty sure that it's not the Hugo's fault.
Then I searched the web and the utterances' issues but could not find the solution either. So I hope someone could help me to solve this tricky problem. Thanks!
Copmuter System: Windows 10 Professional 20H2 and all the apps are the latest.

**Comment by Spphire** [comment]
how did u fix it?

**Comment by SimonYoungCN** [comment]
> how did u fix it?

You can see the solution from [my blog](https://simonyoungcn.github.io/post/traps/#%E8%AF%84%E8%AE%BAutterances).

In the config.toml at the "baseURL" line you should only type `https://[YOUR_GITHUB_ID].github.io/` without the `www.` prefix.

And at the utterances' repo line you should only type the comment repository's name without your GitHub username.

应该是国人吧哈哈😁可以去链接里看一下，网站是用中文写的，以防万一我这个评论就用英文了，后面来的人也看得懂，见谅！
