### ISSUE TITLE
404 - Can not find our issues url

### ISSUE THREAD

**Issue by tatthien** [utterance/utterances#64]
Hi,

Thank you for creating an amazing project.

I'm getting a problem when integrate your application into my project. The app can not find my issues url.

![https://i.imgur.com/avtbXaY.png](https://i.imgur.com/avtbXaY.png)

The repo is containing comments: https://github.com/12bitvn/til-comments

**Comment by nguyenvanduocit** [comment]
You can test here: https://deploy-preview-8--tils.netlify.com/til/2018-08-31.html

**Comment by jdanyow** [comment]
I think you might need to install utterances on the `12bitvn/til-comments` repo.

https://github.com/apps/utterances

**Comment by tatthien** [comment]
I think I've installed it already. But it still does not work.
![https://i.imgur.com/8xmUe3M.png](https://i.imgur.com/8xmUe3M.png)

**Comment by jdanyow** [comment]
it's a bug in the the utterances API- the regex isn't handing your github username because it starts with a number:

https://github.com/utterance/utterances-oauth/blob/1d03304ad6e29e6c370c6515d330e8e6a768085e/src/routes.ts#L35

**Comment by jdanyow** [comment]
fixed in https://github.com/utterance/utterances-oauth/commit/614d94a8d876fe7a77ed6563d7ca600d5e161578

thanks for reporting ✨ 👍

**Comment by tatthien** [comment]
Thank you so much
