### ISSUE TITLE
apps/utterances landing page needs more guidance

### ISSUE THREAD

**Issue by belm0** [utterance/utterances#65]
Please provide more info at https://github.com/apps/utterances, since this page is linked to as "Learn more about utterances" in the permissions flow.  Users not familiar with utterances or the concept of blog comments hosted by github will need a better orientation to decide whether they want to grant permissions.

Thank you for considering

**Comment by jdanyow** [comment]
GitHub limits the amount of text we're able to put in the description. I wasn't able to add much more detail unfortunately.

https://github.com/apps/utterances
