### ISSUE TITLE
Add clickable link to the backing GitHub issue somewhere?

### ISSUE THREAD

**Issue by hartwork** [utterance/utterances#653]
Hi!

When reading https://utteranc.es/ I noticed that there seems to be no way to find the backing GitHub issue other than opening the network tab of the browser and finding the right request. Are there plans to add a clickable link to the backing GitHub issue? I think that would be of value to users curious to see the and compare to the GitHub side of utterances. What do you think?

Best, Sebastian

**Comment by laymonage** [comment]
https://github.com/utterance/utterances/issues/547#issuecomment-1086257772

**Comment by hartwork** [comment]
@laymonage thanks!

I found the mentioned "&lt;number&gt; comments" now:

![comments](https://github.com/utterance/utterances/assets/1577132/c1b1e354-5b4b-48b2-965f-1b83c5e522a9)

I guess that means it's too hard to find? I'm not sure why one would want to click on text "&lt;number&gt; comments" when already viewing comments right below, and the link doesn't show as a link before hover. Don't fix it just for me, but I think it's a bug in UX personally.

**Comment by hartwork** [comment]
Closing to keep https://github.com/issues clean for myself…
