### ISSUE TITLE
Using Discussions instead of Issues?

### ISSUE THREAD

**Issue by LeaVerou** [utterance/utterances#655]
Hey, thanks for making this! What a brilliant idea.

I was wondering if you folks were considering supporting [GitHub Discussions](https://docs.github.com/en/discussions/quickstart) as a comments backend, instead of issues.
This allows limited threading, as well as marking answers, and also seems conceptually more suitable (I could imagine even using the same repo as for the website, whereas I can't do that with a backend that uses Issues, as I need Issues to host — well — actual issues).

**Comment by laymonage** [comment]
See #324 (and check out https://giscus.app 😉)

**Comment by LeaVerou** [comment]
Thanks! Closing this then, since it’s a duplicate.
