### ISSUE TITLE
Bug Report - wrong links base url generation (markdown)

### ISSUE THREAD

**Issue by tarampampam** [utterance/utterances#66]
If you paste this markdown code into comment textarea:

```markdown
[google](google.com)
```

You will see next html-code:

```html
<a href="google.com" target="_blank" rel="noopener">google</a>
```

And it looks ok, but.. no:

![2018-09-12 20-19-35](https://user-images.githubusercontent.com/7326800/45435147-67259c80-b6c9-11e8-8062-5fc67ccbb537.png)

> "Base url" is `https://utteranc.es/`, "iframe" context, relative link

Maybe this need to be fixed?

**Comment by jdanyow** [comment]
Utterances uses the github API to parse and render markdown as html.  If you enter `[google](google.com)` in the comment box of this page, then click on the preview tab and hover the mouse over the resulting link, you'll see the same behavior.
