### ISSUE TITLE
Not issue

### ISSUE THREAD

**Issue by w3teal** [utterance/utterances#664]
Im not have **Issue**... im just want _comment_

**Comment by James-E-A** [comment]
Yeah, it would be nice if there were an option to file [discussions](https://docs.github.com/en/discussions) instead.

**Comment by nschonni** [comment]
If you want to use Discussions, https://github.com/giscus/giscus/ is the project that does it that way

**Comment by w3teal** [comment]
> If you want to use Discussions, https://github.com/giscus/giscus/ is the project that does it that way

Oh, thanks! I will close this issue.
