### ISSUE TITLE
What do you mean by this ?

### ISSUE THREAD

**Issue by ergo9ine** [utterance/utterances#76]
`<script src="https://utteranc.es/client.js"
        repo="ergo9ine/sfdb_tracker"
        issue-term="index"
        theme="github-dark"
        crossorigin="anonymous"
        async></script>`

> SyntaxError: An invalid or illegal string was specified utterances.10cca43d.js:1

**Comment by weyusi** [comment]
utterances doesn't seem to support repo name with underline
https://github.com/utterance/utterances/issues/1#issuecomment-315630670 https://github.com/utterance/utterances/blob/master/src/repo-regex.ts

**Comment by jdanyow** [comment]
@ergo9ine thanks for reporting. The repo regex was not permitting underscores. This is fixed in 5a2aed476eb71c6a5c27757c77a91bca1878d1f0.

**Comment by weyusi** [comment]
`\w` includes underscore. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#Using_special_characters

**Comment by jdanyow** [comment]
Which browser are you seeing the issue in? Could you provide a link to the page?

**Comment by ergo9ine** [comment]
[https://sf2031.com/](https://sf2031.com/)

It's settled.
Thanks!

**Comment by tiagoad** [comment]
I'm getting this same error. My repo name has a dash in it, is that the problem?
