### ISSUE TITLE
Support for email replies

### ISSUE THREAD

**Issue by PhilipVis** [utterance/utterances#84]
Email replies to issues currently show the comments to which the emailer replied without any styling. I would like to ask if it is possible to hide the comment history behind an expand link (...) like on Github and to render it like quoted text similar to Github,  or to just completely hide the comment history in the Utterances comment. 

Example reply:
https://github.com/PhilipVis/philipvis.github.io/issues/3#issuecomment-430946403

To see how this is currently rendered by Utterances, look at the comments section on page https://verummeum.com/blog/2018/10/14/portable-package-formats/.

**Comment by jdanyow** [comment]
fixed- thanks for reporting!
