### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by blackgwe** [utterance/utterances#9]
I got an error if I build the project. It happens in `optimize` step:

`yarn run optimize`

```
[...]
$ inliner --skip-absolute-urls debug/utterances.html > dist/utterances.html 
fs.js:584
  return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
                 ^

Error: ENOENT: no such file or directory, open '/tmp/utterances/node_modules/svgo/lib/svgo/../../.svgo.yml'
    at Error (native)
    at Object.fs.openSync (fs.js:584:18)
    at Object.fs.readFileSync (fs.js:431:33)
    at module.exports (/tmp/utterances/node_modules/svgo/lib/svgo/config.js:31:48)
    at new module.exports (/tmp/utterances/node_modules/svgo/lib/svgo.js:21:19)
```
Please check https://github.com/svg/svgo/issues/622 , maybe it's the solution.

PS: THANK you for opening the source code - you did a great job!

**Comment by jdanyow** [comment]
Hey @blackgwe sorry for the late response. Few questions for you:

- Still occurring?
- Is this happening when you execute `yarn run build` / `yarn run develop` / `yarn run deploy`?
- What platform are you on? windows/mac/linux (i'm on linux and windows)
- Have you tried updating yarn?
- I recently updated a bunch of dependencies, including inliner... maybe this fixed the issue.

**Comment by blackgwe** [comment]
>Still occurring?
You fixed it with updating dependencies - THANKK YOU!!!

**Comment by jdanyow** [comment]
nice :+1:  closing this

**Comment by jdanyow** [comment]
by the way- since you're looking at the source code- I'm starting to switch the project over to GitHub's graphql API since it allows me to fetch the user, issue, comments and config file all in one request. This work is happening in the `graphql` branch. It's mostly complete, just needs testing, etc.
