### ISSUE TITLE
Support for Gitlab

### ISSUE THREAD

**Issue by rootkea** [utterance/utterances#96]
Hi!

I would like to own the data (comments) posted on my website by using the self-hosted Gitlab instance. So is it possible to use Gitlab issues instead of Github issues?

Thanks!

**Comment by VincentTam** [comment]
Why not use [Staticman](https://staticman.net)?  Since eduardoboucas/staticman#219, it's possible to embed comments into the site.

**Comment by rootkea** [comment]
@VincentTam Thank you for suggesting StaticMan!  

I'm toying with it now and will get back to you once I'm done. :)

**Comment by jdanyow** [comment]
staticman :+1:

**Comment by robb-romans** [comment]
Also would love to have GitLab support

**Comment by donaldboulton** [comment]
Staticman died no response from Staticman or Vincent Tams  Staticman Lab on invite or usage!
Staticman does not work any more and if you can get it to work it is overused and timeout errors are constant.
Been using Staticman for years, about 8 months ago it died and so Staticman  no more.
You could fork the repo, updated it = github graphql V-4.
 And then have your own

**Comment by VincentTam** [comment]
@donaldboulton I'm sorry to hear about your experience.  I'm always pingable by `@VincentTam`, and @staticmanlab is _active_ on [GitHub](https://github.com/staticmanlab) and [GitLab.com](https://gitlab.com/staticmanlab).

P.S. Four months ago, I've deployed [_another instance_ on Framagit](https://framagit.org/staticmanlab1) at https://staticman-frama.herokuapp.com/ associated with the user [@staticmanlab1](https://framagit.org/staticmanlab1) after [some user(s)](https://framagit.org/Bridouz/bridouz.frama.io/commit/7dadae4e55d0d232082dc8cae2f357057de05cf8) had failed to add Staticman to their static sites on [Framagit](https://framagit.org).

**Comment by sunk818** [comment]
I'd like GitLab support because of the additional ways you can login using social media accounts. This will make commenting easier than just a github login. My instance is self-hosted so it is not using GitHub, GitLab, etc.

**Comment by phaitonican** [comment]
same here would be awesome. RN i have my pages hosted on gitlab and my utternance points to github its kind of strange but does not really matterr, i stttill prefer gitlab over github

**Comment by mrsnakeoil** [comment]
I would very much like to see this supported for a number of reasons (below). As for what I can offer,  whilst I'm not up to making the changes, can help QA, support, documentation, and provide cookies/pizza by post!

1. **Broader Reach and Inclusivity**: Not all developers and organizations use GitHub; some prefer GitLab for various reasons, including its open-source nature and unique features. Supporting GitLab would make Utterances accessible to a wider audience.
2. **Diversification of Platform Dependencies**: Relying solely on GitHub might pose risks if there are service disruptions or policy changes. Supporting GitLab provides a backup, ensuring continuous service availability.
3. **Open Source Alignment**: Like GitHub, GitLab is popular in the open-source community. Supporting it aligns with the ethos of open-source development and broadens the tool's appeal to open-source projects.
4. **Competitive Edge**: By supporting multiple platforms, Utterances can differentiate itself from other commenting widgets that may only support one platform, thus attracting users looking for multi-platform solutions.
5. **Community Building**: Supporting GitLab can help build a community of users who are enthusiastic about GitLab, fostering a sense of inclusivity and diversity in the user base.
